### ISSUE TITLE
Proofreading: WRIO Internet OS

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1152]
Please proofread https://docs.google.com/document/d/1kdKoDfp9mT5M4pssJTqvA6sw4zzYQ5HFaN-osu7J-Nk/edit?usp=sharing

**Comment by AlexeyAnshakov** [comment]
ETA?

**Comment by ghost** [comment]
I have only view only on this could you enable edit mode

**Comment by ghost** [comment]
I didn't take off desiree -- not sure what just happened...

**Comment by AlexeyAnshakov** [comment]
@jaezed you have been added as an editor.

**Comment by ghost** [comment]
Thanks

**Comment by ghost** [comment]
is this ok? - do you have any other updates on this?

**Comment by AlexeyAnshakov** [comment]
Thank you, we're ok for now. At the moment we need to push with contacts.
