### ISSUE TITLE
Hubs text

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1207]
Before ICO and global PR company we have to create short but well-written texts for all dApps 
https://pinger.wrioos.com
https://webgold.wrioos.com
https://core.wrioos.com/
etc.

**Comment by AlWaleed84** [comment]
@jaezed Can you have a look at this please.  

We need to revamp some verbiage if need be, it can be written in a PDF and shared here.

**Comment by ghost** [comment]
[Birth of The Sun.docx](https://github.com/webRunes/WRIO-InternetOS/files/1342664/Birth.of.The.Sun.docx)
Hi There

Here is a draft -- the titter info is still there so that needs to change -- what have we decided on?
LMK any changes and I can review it again.  
There wasn't a ton of changes -- just a bit 👍 

[Birth of The Sun.pdf](https://github.com/webRunes/WRIO-InternetOS/files/1342663/Birth.of.The.Sun.pdf)

**Comment by AlexeyAnshakov** [comment]
We have to add details from the WP. We will return to the task after Core editor update, so you can improve pages by yourselves.

**Comment by AlexeyAnshakov** [comment]
We also need to rewrite https://webrunes.com text.

**Comment by ghost** [comment]
ok
ᐧ
j.

**Comment by ghost** [comment]
Do you want me to just add it as a word text doc here? for the website 

And can you assign this to me so it shows up in my dropdown menu

**Comment by AlexeyAnshakov** [comment]
@jaezed seems I have to rewrite all of them by myself, but try to rewrite webrunes.com using WP. Check some ICO succesfull projects as an example. Keep in mind webrunes.com is about our team, not WRIO OS. It has an own hub.

**Comment by ghost** [comment]
https://docs.google.com/document/d/1V8oGYbZU_ml3-is65yMFQgZiPtEKs6bl2apu_5KcfLo/edit?usp=sharing

I've edited it -- if you want it 100% different lmk

I think it is ok as it is about the "foundation" and back story -- not the specific iOS project..

Is there any other information about the team specifics that you'd like me to add?

**Comment by AlexeyAnshakov** [comment]
Thanks, I'll check soon. We need to update a team members description (we're working on UI yet and it'll looks like Team section). Please add yourself (info only, I'll update on the hub by myself) and Waleed. @AlWaleed84 what about our new team members, especially GH? Please let Jillian know if we're ready to add.

**Comment by ghost** [comment]
@AlexeyAnshakov what kind of information do you want to have included in the team member description? 

@AlWaleed84 who needs to be added?

**Comment by AlexeyAnshakov** [comment]
Please check a few ICO successful projects as a guide to learn what info must be included for team members. Use team members linkedin profiles.

**Comment by ghost** [comment]
Ok -- that's clear enough - Just who needs to be included?

**Comment by AlexeyAnshakov** [comment]
The same https://webrunes.com/team/ +  
>Please add yourself and Waleed.

**Comment by AlexeyAnshakov** [comment]
https://docs.google.com/document/d/1V8oGYbZU_ml3-is65yMFQgZiPtEKs6bl2apu_5KcfLo/edit is ready. Will be implemented later.

**Comment by ghost** [comment]
Great also here is the share link for team updates
https://docs.google.com/document/d/1r5Yse5ymLtazZeAl_oEqhOX3-H4PnqJ6dU5UBP1LrLA/edit?usp=sharing
ᐧ
j.

**Comment by AlexeyAnshakov** [comment]
Please update all others team members as well.

**Comment by ghost** [comment]
ok
is that style ok? or did you want more information per person?
ᐧ
j.

**Comment by AlexeyAnshakov** [comment]
Looks good

**Comment by ghost** [comment]
Ok I've added some more - the other ones were a little more complicated but
change it however you like :)
ᐧ
j.

**Comment by AlexeyAnshakov** [comment]
webRunes Team https://webrunes.com/team/ completed. We'll fix UI next week, update Sophia ticket and add two more members.

**Comment by AlexeyAnshakov** [comment]
wrioos.com text completed and will be translated soon. Previos text moved to the WRIO Internet OS book (in progress).

**Comment by AlexeyAnshakov** [comment]
@jaezed please try to improve text for
https://titter.wrioos.com (will be renamed soon)
https://core.wrioos.com
https://webgold.wrioos.com

**Comment by ghost** [comment]
Okey Doke Will do this shortly

ᐧ

j.

**Comment by ghost** [comment]
Hi Alexey I already did this a week ago --

it was uploaded as a pdf

I've added it to google drive -- did you want me to go over the text again?

https://docs.google.com/document/d/1TASHOnmfaazQXZGp4IkYfqevh-Rgq9yDWP1jH6Jf2gk/edit?usp=sharing


ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
>did you want me to go over the text again?

Jillian, thanks, ok for now. But:
>We have to add details from the WP

and edit the last one:
https://alternative.webrunes.org
after the WP completion.

**Comment by ghost** [comment]
is this done and ok?

**Comment by AlexeyAnshakov** [comment]
I'm still working on the Covers and Offers text, plus other hubs text need improvements - going to send later.

**Comment by AlexeyAnshakov** [comment]
@jaezed please help to re-write and simplify our https://webrunes.com/ hub. We'll add one more section "Blog".
https://docs.google.com/document/d/1XaARfqxqJCv1SCV7A0Ju8FL-15lbWWo7Z3bfMQwiSuo/edit?usp=sharing

**Comment by ghost** [comment]
Hi Alexey


https://docs.google.com/document/d/1V8oGYbZU_ml3-is65yMFQgZiPtEKs6bl2apu_5KcfLo/edit

Please let me know what other edits you'd like to see.

Thanks

ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
Vitali Hatalski added to the team https://webrunes.com/team
