### ISSUE TITLE
Publish

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1233]
We have to find resources like http://icocrowd.com and send our materials right after ICO start.
Please add links.

Press releases:
tips[at]allthingsd.com
tips[at]businessinsider.com
news[at]centernetworks.com
tips[at]geekwire.com
press-leads[at]gigaom.com
new[at]infoq.com
tips[at]inquisitr.com
editorial[at]kernelmag.com
tips[at]lifehacker.com
muonews[at]makeuseof.com
tips[at]pandodaily.com
ashish[at]pluggd.in
tips[at]readwriteweb.com
hello[at]splatf.com
editors[at]tech.li
tips[at]thenextweb.com
tips[at]venturebeat.com
tips[at]xconomy.com

Through a web-form:
http://icocrowd.com
https://bitcointalk.org
https://nlnet.nl/foundation/can_do.html
http://www.icocalendar.today/list-initial-coin-offering-ico.html
https://news.ycombinator.com/submit
https://www.thunderclap.it/
https://www.startupinvesting.org 
https://digg.com/ 
https://techcrunch.com/got-a-tip/
https://www.f6s.com/deals
https://wefunder.com 
https://betaworks.com/fund/
http://paperclipventures.com/page-contact.html
http://arstechnica.com/site/contact-ars-technica.ars
http://boingboing.net/suggest.html
http://www.dailytech.com/ContactStaff.aspx?id=14
http://www.killerstartups.com/contact/
http://mashable.com/tip/
http://www.sitepoint.com/contact/
http://www.theverge.com/tip-us
http://www.techdirt.com/submitstory.php
http://www.techvibes.com/contact
http://techcocktail.com/submit-news-tips
https://www.coindesk.com
http://icocrowd.com/
https://cyber.fund
http://forms.theregister.co.uk/mail_the_reg/?user=newslist
Check out another ICO pages like this https://www.everex.io/ to take out "Media Mentions" links and write to them.
https://habrahabr.ru/company/everydaytools/blog/316722/ [Ru]

Find people like
https://www.linkedin.com/in/jonsouthurst
https://www.linkedin.com/in/dhqngo/
https://www.linkedin.com/in/nuno-miguel-pereira-menezes-a25b019b
https://www.linkedin.com/in/evan-faggart-299483117 
https://fr.linkedin.com/in/sionstevens/en 
and people on FB with blockchain/cryptocurrency/ICO interests and contact them and ask their help to publish about the project.
Find ppl who wrote about Ethereum, perhaps they would like to write about us as well.
Find LinkedIn semantics/blockchain/cryptocurrency/ICO groups and publish about the project.

Cryptomudra wrote to us:
```
We also provide dedicated support to promote ICOs.
...
As a appreciation to your inputs, we would like to write a story about your products, service, blog, and crypto-related work you do on cryptomudra.com.
```
http://vrcontent.com invited us to post on their website as well.

We also have to work with people like
https://angel.co/rogerkver
https://angel.co/hnshah
on angel.co
and who works with the semantic web like
http://www.greggkellogg.net/
or
https://lists.w3.org/Archives/Public/public-schemaorg/ 

Twitter accounts:
allthingsd
betabeat
building43
centernetworks
geekwire
gigaom
JohnHCook 
karaswisher
makeuseof
mashablehq
paidcontent
pandodaily
RWW
sai
sitepoint
TechCocktail
techdirt
techDOTli
techvibes
ToddBishop
twitter.ars
venturebeat
verge
waltmossberg

Find press list on
https://aeron.aero/
We have to find more ICO examples and publish there.

Rating
https://tokentops.com/ico/
http://icorating.com/
https://www.icorating.info
https://ico4you.com/

Find resources, videos, posts like this one
https://www.slideshare.net/icaromedeiros/linked-data-in-use-front-in-bahia-2014
and add comment about our project.

Help links
http://www.michaelseibel.com/blog/how-to-email-early-stage-investors

I'll ask every team member to send a message to their contacts on LinkedIn, angel.co, FB and etc. to join our ICO on best terms (+50% bonus).

**Comment by AlexeyAnshakov** [comment]
@desireedickerson please create a message text for people above. I think we need 2 versions: one for bloggers and another for entrepreneurs, who're interested to be part of our ICO.

**Comment by desireedickerson** [comment]
What were you thinking for this? Do you want me to write verbatim what we would like them to post? Or do you want me to write something that talks about the project and they can then write what they want about it?

Also, what were you thinking in terms of length?

**Comment by AlexeyAnshakov** [comment]
>Do you want me to write verbatim what we would like them to post?

you're free to show creativity in any way: you may ask them to repost or write their own posts, retweet and so on. First of all we have to find early adopters - bloggers, user, etc. everyone who're interested in the semantic web, blockchain and ethereum. We must ask them to publish about us and spread the word in any way.
We call it "a reward", but in fact it's just a gratitude sign, find Promotion offer at https://wrioos.com/. Early adopters will be able to be a cofounders by spending those WRG for equity while https://wrioos.com/dao/investments_and_tokens/#Series_A

The main goal is to create a community that will become our first ICO partners.

I'm going to publish https://goo.gl/MsOfRs and "WRIO Internet OS. Part 1: Vision of the Future Internet" soon, that's the point where you can start from.

**Comment by AlexeyAnshakov** [comment]
Rating
https://tokentops.com/ico/
http://icorating.com/
https://www.icorating.info
https://ico4you.com/

**Comment by ghost** [comment]
Hi @AlexeyAnshakov has any of this been done? - do you want me to create what was asked for above? - Thanks!

**Comment by AlexeyAnshakov** [comment]
@jaezed no progress there yet. Please coordinate with @AlWaleed84

**Comment by ghost** [comment]
Got it 
@alwaleed84 let’s chat today so we can align it up - ping me :) I’m online all day

**Comment by AlexeyAnshakov** [comment]
Any progress?

**Comment by AlexeyAnshakov** [comment]
We're going to use addition marketing fund to be published.

**Comment by ghost** [comment]
​Ok - - I think for this just listing on the top ones that are paid is
sufficient
It's fairly expensive...

Have we thought of doing google ads?​
ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
Not effective, as facebook ads.

**Comment by ghost** [comment]
you can't do facebook ads any more...



ᐧ

j.
