### ISSUE TITLE
Growth hacking strategy

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1245]
Please create a plan of Growth Hacking Strategy. What have to be done to be success with ICO.
@AlWaleed84 @desireedickerson please add your comments if you have ones.

Find more resources like this
https://www.coingecko.com/ico?locale=en
to get listed while ICO to attarct more attention.

**Comment by AlexeyAnshakov** [comment]
Please use https://github.com/webRunes/WRIO-InternetOS/issues/1246 after completion.

**Comment by AlexeyAnshakov** [comment]
We have to do the same https://bitcointalk.org/index.php?topic=2036653 to create and grow our community.
https://github.com/webRunes/WRIO-InternetOS/issues/1256

**Comment by AlexeyAnshakov** [comment]
https://github.com/webRunes/WRIO-InternetOS/issues/1248

**Comment by AlWaleed84** [comment]
### Social websites to be active in for community exposure/project visibility:
**1-** Bitcointalk.org    _(Announcement)_
Full project introduction with completed diagrams/graphics,  clear presentation on what is webRunes with no room for questions to be raised, comprehensive white-paper and a clear, well estimated roadmap of the project.

**2-** Medium.com post    _(Formal Announcement)_
Same as Bitcointalk.org post, while including more technical details in these posts.

**3-** Reddit r/cryptocurrency, r/ethereum    _(Engagement)_
Introducing project clearly to /r/ethereum and a link to Medium.com post.

**4-** webRunes Twitter activity    _(All Updates+Engagement)_
Daily/bi-weekly updates on current events, technical challenges, small statements reflecting goals etc.

**5-** Quora   _(Brand awareness)_
Use FAQ (will be in the WP) for this.

### ICO Listing websites for visibility/crowd notification:
- https://www.smithandcrown.com/icos/
   ^ ICO listings, and reviews.
- https://www.icoalert.com/
- https://www.coingecko.com/ico?locale=en
- https://www.ico-list.com/
- https://icotracker.net/
- https://www.coinschedule.com/

However, most these websites would list the ICO once some community outreach is present.


### ICO Launching services we have contacted: (white-paper needed to further discussions)

_Known trusted sources for listing ICO's:_   (will list more if found)
- Zeppelin Solutions https://zeppelin.solutions/escrow
- Token Market https://tokenmarket.net/ico-professional-services

_ICO Consulting, Marketing:_
- Sutton Stone https://suttonstone.com/ico-consulting/



_...to be updated_

**Comment by desireedickerson** [comment]
I think this is a good list. There a quite a few additional subreddits we can probably engage with as well. I think we really need to get the Twitter feed going. Even if it is just retweeting other relevant users, commenting, and liking tweets. It will at least help us grow a community and have an audience to reach to at ICO. Thoughts?

**Comment by AlexeyAnshakov** [comment]
It'll take a lot of time: search tweets and retweet. Without original content, I do not believe that we will succeed. Anyway, we need a bitcoin/reddit community. They have a relevant audience.

**Comment by Shathyan** [comment]
Quora is one good medium where we can write & promote. We ourself can post questions from the buyer point of view & answer from our official account. This can give us more visibility & also brand trust for the buyers

**Comment by AlexeyAnshakov** [comment]
@Shathyan true. We'll use our FAQ for this. Thanks for the contribution.

**Comment by Shathyan** [comment]
I feel the success an ICO mostly depends on how the investors trust us. The 2 key points are
- Our WhitePaper
- Our Branding ( Gain more trust from the investors )

For Brand & Trust;
We should try to get a coverage on Forbes, Tech Crunch, Mashable etc which will add more trust.
Also blogs or communities which talk about Crypto-Currency like Steemit.com

**Comment by AlexeyAnshakov** [comment]
That's the point of https://github.com/webRunes/WRIO-InternetOS/issues/1233

**Comment by desireedickerson** [comment]
@AlexeyAnshakov definitely agree. Just thinking that we should promote somewhat BEFORE the ICO, about the ICO. But waiting if fine too!

**Comment by AlexeyAnshakov** [comment]
@desireedickerson I believe that Reddit, Bitcointalk and Linkedin groups (like this guy follows https://www.linkedin.com/in/porat-elad-540ab0145/) are best places for promotion. We have to publish our first posts there soon.
https://www.linkedin.com/groups/8623314/profile another group example

**Comment by AlexeyAnshakov** [comment]
Check out https://icobench.com/

example of their grade on the ICO page
https://aeron.aero/

**Comment by AlexeyAnshakov** [comment]
http://ratei.co

**Comment by AlexeyAnshakov** [comment]
We have to spread the word through communities like https://opendata.stackexchange.com/

**Comment by AlexeyAnshakov** [comment]
Get listed on services "We Are Listed On" http://www.rpay.io/

**Comment by AlexeyAnshakov** [comment]
http://ratei.co
upd 8 oct:
http://icodude.com/
http://icocrowd.com/calendar/
find more on https://duckduckgo.com/?q=ico+calendar&ia=web and update the list. We have to be listed on as much as we can.
upd 11 oct:
https://www.coindesk.com/the-ultimate-list-of-resources-for-researching-and-launching-icos/
https://www.ico-list.com/Index/detail/id/123.html
upd 22 oct:
https://www.trackico.io/
http://icopitch.com/
https://coinmarketcap.com/
http://whattomine.com/
http://coingecko.com/
http://icoage.com/
http://icoalert.com/
https://icotracker.net/
https://www.coinschedule.com/
http://icocountdown.com/
https://www.investitin.com/ico/
upd 31 oct:
http://www.ico-lister.com

Check out https://icobench.com/
example of their grade on the ICO page
https://aeron.aero/

**Comment by AlexeyAnshakov** [comment]
https://www.trackico.io/
http://icopitch.com/
https://coinmarketcap.com/
http://whattomine.com/
http://coingecko.com/
http://icoage.com/
http://icoalert.com/
https://icotracker.net/
https://www.coinschedule.com/
http://icocountdown.com/
https://www.investitin.com/ico/

**Comment by ghost** [comment]
Have we been listed on all of these? -- I've started a google sheet to keep
track

https://docs.google.com/spreadsheets/d/1JrF_P29n_15ScvIVt9DmorrgkeFwkkqc4TA8RcP1u8w/edit?usp=sharing
I will add more as they come up -- but please LMK if we are already listed
on these
ᐧ
j.

**Comment by AlexeyAnshakov** [comment]
Not yet, but we should.

**Comment by ghost** [comment]
Ok
I've created the list to keep track
I will also update it as we add more - You can use it or not whatever works
for you
j.

**Comment by AlexeyAnshakov** [comment]
Please find social media groups, websites and forums of https://en.wikipedia.org/wiki/Cypherpunk to promote us. We have to show that the project adhere to the cypher-ideology.
Use it: https://player.fm/podcasts/Cypherpunks
https://en.wikipedia.org/wiki/Phrack
https://en.wikipedia.org/wiki/2600:_The_Hacker_Quarterly
https://en.wikipedia.org/wiki/Wired_(magazine)
please find more.
@AlWaleed84 we've to contact https://en.wikipedia.org/wiki/Cypherpunk#Noteworthy_cypherpunks to find support.

**Comment by AlexeyAnshakov** [comment]
Perhaps we should use their service https://www.linkedin.com/in/joeacosta
I suppose we should use premium linkedin features while ICO to write directly to ppl.

**Comment by AlexeyAnshakov** [comment]
https://blockchainhub.net/blog/blog/how-to-do-an-ico-initial-coin-offering

**Comment by AlexeyAnshakov** [comment]
https://opendatacommunity.slack.com/ find more Slack channels to promote us.

**Comment by ghost** [comment]
Hi There --
Is there a telegram chat that we can start as well? -- or is there one? I
searched it but couldnt' find one
ᐧ
j.

**Comment by AlexeyAnshakov** [comment]
No, why do we need it?

**Comment by ghost** [comment]
I see that a lot of ICOs are using telegram chat more so than slack
ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
True, but it's doesnt' answer "why". One channel is enough, no need to spray our small resources to support multiple channels.

**Comment by ghost** [comment]
Slack is not being used as much for ICOs - the shift is towards telegram

If we are launching the ICO in January - it would be beneficial to have a
solid account set up now - and start getting traction through it before the
ICO launch.

I understand that it is technically the same thing - but if you look at
bitcointalk ico ann threads  - telegram is where people are being directed
- not slack. - just an observation.
ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
I'm not against telegram, I just don't see the point to use it. I'm ok if you start it with @AlWaleed84 , but if the main gate is bitcointalks, there no point to promote there telegram or smt. else, if users already found us.

**Comment by AlexeyAnshakov** [comment]
Please find more channels https://telegram.me/icodigestcom

**Comment by ghost** [comment]
@thecoinfarm
@tokenmarket
@cryptomining
@icocountdown
@bitcoinchannel
@cryptocurrency
@blockfolio
@bitcoinnews
@myceliumwallet
@bitnationchat
@trollbox
@bitcoinaustralia
@btcfork
@bitcoincore
@smartcontracts
@bitcoin_unlimited
@btccom
@bitcoinchat
@bitcoinuk
@otctrade
@ethclassic
@bitmonero
@rsksmart
@whaleclub
@whalepoolbtc
@counterparty
@melonport
@startcoinuncensored
@viacoin
@zcashco
@storjproject
@www_Bitcoin_com
@cryptocurrency
@shitcoincharts
@bitcoinnews
@openledger
@cryptosnippets
@bitcoinblink
@hodlhodlnews
@finexdrama
@litecoin
@maidsafecoin
@monero
@namecoin
@navcoin
@nemred
@nxtcommunity
@peercoin
@radiumofficial
@ripple
@shadowcash
@omnilayer
@siacoin
@steem_en
@iotatangle
@synereo
@zcashco
ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
Please add these contact to our doc file.
We'll try to spend some $$$ to promote our intro on Youtube.

**Comment by AlexeyAnshakov** [comment]
@AlWaleed84 I sent you an email from Paul Smith. Perhaps we can use his services right after ICO start.

**Comment by AlexeyAnshakov** [comment]
To increase the chance to attract investors, every message must be personal. No need to dig a lot, just a few words why we wrote to him/her: "we found out that you're interested in [cryptocurrencies, cryptoeconomy, political freedom and so on. Based on info from the social media profile]", that's why we believe you'll be interested... etc.

**Comment by AlexeyAnshakov** [comment]
Another ICO catalogue https://ico-digest.com/

**Comment by ghost** [comment]
@AlWaleed84 do we have a new growth hacker?

I have a list of contacts - that you can contact for crypto related news features maybe shared in google drive

**Comment by AlexeyAnshakov** [comment]
http://bigbreak101.com/ico-services/ we can use 
PR AND PRESS CAMPAIGN
BOUNTY CAMPAIGN
OUR PAST CONTRIBUTORS ENGAGEMENT
ICO LISTING SUBMISSION ASSISTANCE

**Comment by AlexeyAnshakov** [comment]
Please prepare (use @Hexah07 help) a list of bloggers and youtubers like this one https://www.youtube.com/watch?v=Wa0gCSzc26w. We're going to send them info about the proj and ask theirs info support. Find at least 250 authors.

**Comment by AlexeyAnshakov** [comment]
@jaezed @benjamin421 please reread the issue, use info to update current issues, create a new ones if needed and close this one.

**Comment by consciousrepo** [comment]
Offer from @cryptosocialMads
$ 280 banner
$ 230 timeline
$ 180 sidebar
$ 180 Post in CryptoBlog
in token equivalent
1 month duration

**Comment by RoySasson** [comment]
If they believe their traffic is good maybe we can do performance based deal ? Display advertising is tricky since you can't tell how good is their traffic until you tried it

----- הודעה מקורית -----
מאת: "Benjamin Anderson" <notifications@github.com>
נשלח: ‎09/‎05/‎2018 21:49
אל: "webRunes/WRIO-InternetOS" <WRIO-InternetOS@noreply.github.com>
עותק: "Subscribed" <subscribed@noreply.github.com>
נושא: Re: [webRunes/WRIO-InternetOS] Growth hacking strategy (#1245)

Offer from @cryptosocialmads
$ 280 banner
$ 230 timeline
$ 180 sidebar
$ 180 Post in CryptoBlog
in token equivalent
1 month duration

**Comment by consciousrepo** [comment]
Everyone with a larger following I'm reaching out to and hearing back from seems to be most interested in paid advertising even if our followings match closely, they'd rather be paid for the service. Some of the offers:
https://www.youtube.com/user/NiedzwiedzTheGamer 15 minute video here for 2 ETH
These all ran by same, didn't want to cross  promote and initially wanted BTC but he he's open to token payment, still in negotiation.
1st one: https://www.youtube.com/user/extremalneparodie
2nd one: https://www.youtube.com/channel/UCnD9lXzUi56YW3V5BPTO8fg
3rd one: https://www.youtube.com/user/NiedzwiedzTheGamer
A quote from the manager of ICO_Telegraph-
1) Regular Post - 0.1 BTC (short description of your project / ICO)
2) Full review of ICO, plus detailed description of all the pros - 0.13 BTC
3) Full analysis with an urgent advice to invest + a note that this is NOT advertising + mentioning that we invested ourselves - 0.17 BTC
4) 3 separate publications within a week that will remind users about your ICO. The implementation is totally native, for example, in one of the news posts - 0.1 BTC
5) Additionally, leave the post in the top for a week - 0.08 BTC
6) Notification of the post 4 days in a row -0.1 BTC (only if the post is in the top)

If you select several options we provide discounts. 

We also accept payment with ETH (at the exchange rate of the payment moment). 

A special offer
 1 + 2 + 3 + 4 + 5 + 6 = 0.5 BTC (instead of 0.68 BTC).
3 + 4 + 5 + 6 = 0.33 BTC (instead of 0.45 BTC).

Then there was https://t.me/joinchat/AAAAAESKJhBDc_VEtv9RPA
And they're hapoy to croas promote but want it in our announcement channel not the group channel.

**Comment by consciousrepo** [comment]
And @roy I'll reach back out and see if they're open to that

**Comment by AlexeyAnshakov** [comment]
>ICO_Telegraph

What's the link?

**Comment by consciousrepo** [comment]
My text below their user was their offer

**Comment by AlexeyAnshakov** [comment]
Ok, if they accept WGD, we will use their service right after crowdsale starts.

**Comment by consciousrepo** [comment]
👍

**Comment by AlexeyAnshakov** [comment]
@benjamin421 please move info into https://docs.google.com/spreadsheets/d/1XvKnOqrJQ4knKI0GhhxJpB84J36aYrcpgmBrn3i3Vfk/edit#gid=0

@RoySasson please be sure we're listed at
https://www.smithandcrown.com/icos/
https://www.icoalert.com/
https://www.coingecko.com/ico?locale=en
https://www.ico-list.com/
https://icotracker.net/
https://www.coinschedule.com/
https://tokenmarket.net
and check other links in the thread above.
