### ISSUE TITLE
Post based on the table diagram

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1246]
@desireedickerson please create post based on 
https://files.slack.com/files-pri/T596JK7RN-F6MSDREEP/table.png
You may use the source of the original image https://www.nirandfar.com/2012/01/where-is-web-going.html for inpiration.
@AlWaleed84 please help @desireedickerson and coordinate the process.
We'll publish it in our blog with "WRIO Internet OS. Vision of the Future Internet".

**Comment by desireedickerson** [comment]
Monday

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by AlexeyAnshakov** [comment]
https://medium.com/@Circa84/caf558019980
