### ISSUE TITLE
Linkedin contacts

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1250]
Please start adding Linkedin contacts: IT investors, semantic web and blockchain enthusiasts. People who might be interested in our ICO, so you will be able to send them invitations after ICO start. I believe we need at least 1000 contacts.

**Comment by AlWaleed84** [comment]
List will/should be updated with atleast 500 contacts by the end of ~~August~~ September.
### 
Contacts of Relevance to WRIO Internet OS project:
-https://www.linkedin.com/in/mattasher
-https://www.linkedin.com/in/carlnichols
-https://www.linkedin.com/in/ameerrosic/
-https://www.linkedin.com/in/chiefapricot/
-https://www.linkedin.com/in/williammougayar/
-https://www.linkedin.com/in/jg1578/
-https://www.linkedin.com/in/pbartstephens/
-https://www.linkedin.com/in/spencer-bogart-cfa-bba645a/
-https://www.linkedin.com/in/nicklasmillgaard
-https://www.linkedin.com/in/thomas-irwin-2802b5138
-https://www.linkedin.com/in/eduardogece/
-https://www.linkedin.com/in/beniaminmincu
-https://www.linkedin.com/in/denisbarry
-https://www.linkedin.com/in/cherkashin/
-https://www.linkedin.com/in/adamstradling/
-https://www.linkedin.com/in/edward-moncada-47564118
-https://www.linkedin.com/in/kristiangerard/

updated>12/9/17
https://www.linkedin.com/in/nav-dhinsa-1400409
updated>27/9/17
https://www.linkedin.com/in/nicolasragot22

**Comment by AlexeyAnshakov** [comment]
Please find and join a proper Linkedin groups as well.

**Comment by AlexeyAnshakov** [comment]
ETA?

**Comment by AlexeyAnshakov** [comment]
A couple of links
https://www.linkedin.com/in/mattasher
https://www.linkedin.com/in/carlnichols

**Comment by AlexeyAnshakov** [comment]
Any progress?

**Comment by AlWaleed84** [comment]
update/

**Comment by ghost** [comment]
Ok noted

**Comment by AlexeyAnshakov** [comment]
How it's going? How many contacts and groups you added?

**Comment by AlexeyAnshakov** [comment]
Find investors and contact them using https://wefunder.com/explore
open proper projects and find investors tab, contact them via Linkedin.

**Comment by AlexeyAnshakov** [comment]
@jaezed what progress?

**Comment by AlexeyAnshakov** [comment]
Use https://www.crunchbase.com/app/search/investors/2df0aa480a2ebb01c193bffa06ba96af0fa74c9b as well

**Comment by ghost** [comment]
Thank you alexey will add a pile tonight using the resources you sent.

**Comment by ghost** [comment]
I've updated some linked in contacts -- and will add some groups to join as well

**Comment by ghost** [comment]
Please let me know -- My LinkedIn professional expires tomorrow -- I will update the contact chart using the other methods onwards.

**Comment by AlexeyAnshakov** [comment]
>My LinkedIn professional expires

No prob, there a lot of contacts on angel.co and crunchbase.com

**Comment by ghost** [comment]
OK I will add more this week from those sources - 

Alwaleed - what is your progress with adding the contacts and groups? - are they any good?

Thanks

**Comment by ghost** [comment]
@AlWaleed84 Just checking in to see where we are with this? are we at 1000?

**Comment by AlexeyAnshakov** [comment]
Progress?
@jaezed are they added to the your contacts or just listed in the doc?

**Comment by AlexeyAnshakov** [comment]
>Please find and join a proper Linkedin groups as well.

@jaezed please add list of groups

**Comment by ghost** [comment]
Hi Alexey

I've added a list of groups - I can only search for so many groups at a
time on the free account --

Waleed what is your progress on this?
ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
@jaezed I can't find the list of groups in the doc. How many of them you've joined so far?

**Comment by ghost** [comment]
I’ve joined 15 

They are the last links on the list

**Comment by AlexeyAnshakov** [comment]
>Use https://www.crunchbase.com/app/search/investors/2df0aa480a2ebb01c193bffa06ba96af0fa74c9b as well

Did you use it?

**Comment by AlexeyAnshakov** [comment]
One more group https://www.linkedin.com/groups/13552653/profile 
Please contact members and find more slack community like https://www.blockcrush.com/

**Comment by ghost** [comment]
@AlWaleed84 What is the progress on this?

**Comment by AlexeyAnshakov** [comment]
What progress and how many linkedin group you've joined?

**Comment by ghost** [comment]
Hi alexey 

I’ve joined as many as I am able to - however posting and contact rules are different in each one but generally to avoid getting banned you are not allowed to promote icos in anyway.

Just a heads up on that.

**Comment by AlexeyAnshakov** [comment]
For these cases we're going to prepare the poll. The poll will contain the link to wrio os.

**Comment by AlexeyAnshakov** [comment]
Be ready to send soon.

**Comment by ghost** [comment]
@Alwaleed - I sent the list of the ones i found - but I am assuming you
have more than that in your account to contact. Please confirm with Alexey

Thanks
ᐧ

j.
