### ISSUE TITLE
webGold exchanges listing

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1251]
We must be ready to be included in the list on https://www.poloniex.com or/and https://www.kraken.com.
Please find out what must be done for it.

**Comment by AlWaleed84** [comment]
**Exchanges for possible listing:**
- www.etherdelta.com
- www.liqui.io
- www.poloniex.com
- www.kraken.com
- www.bittrex.com
- www.binance.com
- www.bitfinex.com
- www.bter.com
- www.allcoin.com
- www.gatecoin.com
- www.yobit.net

_Arrangements to be made 60 days maximum.. prior to ICO  (listing fees, negotiations.. etc.)_

**Comment by AlexeyAnshakov** [comment]
For the moment https://labs.binance.com/ seems is the most useful platform. For sure we have to contact all of them. Please cooperate with Eric and use @benjamin421 help if needed.

**Comment by consciousrepo** [comment]
I'll help in any way I can👍
