### ISSUE TITLE
Bounty campaign google form

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1256]
We must create a bounty campaign like https://bitcointalk.org/index.php?topic=2051760.0 to grow our community.
Find out other companies for details and create our own.

After that please create a google bounty campaign form. We're going to add it on wrioos.com.
https://docs.google.com/forms/d/1FenjvtJmmClY8uCVxkhGE6qVmphc-XbocofaRpveVYY/edit?usp=sharing

Use Desiree and Jillian help.

**Comment by AlexeyAnshakov** [comment]
Please contact these people https://docs.google.com/spreadsheets/d/1aNwz2-88S8y2IkQxeiOUdbRMbxNA0w9hV5qPlg2FX88/edit#gid=324023818 and propose to join our bounty campaign.
12 oct upd
https://docs.google.com/spreadsheets/d/1lhBUvwhrVwT1eeTbH6Ld_XY5PAH5rXWRusCa3KdAOiI

Go through treads on https://bitcointalk.org/index.php?board=238.0
to find Participants links like this one
https://docs.google.com/spreadsheets/d/1iM59i-_j64XpTsguN82_jMajZsdSKKadYK3Ru1e7GWA/edit#gid=0
so you can send them an invite to participate in our campaign as well. We need at least 1,000 invitations.

More links https://bitcointalk.org/index.php?topic=1980698.0

@jaezed please scan https://bitcointalk.org and find more docs with "bounty campaign hunters" contacts, so we can invite them.

**Comment by AlexeyAnshakov** [comment]
ETA?

**Comment by desireedickerson** [comment]
Tomorrow

**Comment by AlexeyAnshakov** [comment]
Please add a reward for bloggers who are going to write about us. They can use our WP, images or whatever for their posts.

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by AlexeyAnshakov** [comment]
Add 10,000WRG (per publish) reward for digg, mashable and others press release authors. So we can add the list like they did https://cartaxi.io/

Upd: lets stand on reward per like and share.

**Comment by AlWaleed84** [comment]
Sure, I'll add that to our original post. 

That's a good idea. 

AlWaleed K. AlShehail

**Comment by AlexeyAnshakov** [comment]
Add option: 
- write social posts based on WP + Pre-order form inside
So users can get rewards per share/like and referal program
https://github.com/webRunes/WRIO-InternetOS/issues/1258#issuecomment-330504758

**Comment by desireedickerson** [comment]
made some updates. thoughts?

**Comment by AlexeyAnshakov** [comment]
We have to add a grade like they did
>Texts creators receive 250, 500, or 1000 ZenTokens depending on the quality of their posts.
https://bitcointalk.org/index.php?topic=2051760.0

**Comment by AlexeyAnshakov** [comment]
We have to add a grade like they did
>Texts creators receive 250, 500, or 1000 ZenTokens depending on the quality of their posts.

https://bitcointalk.org/index.php?topic=2051760.0

+Bounty Campaigns except "Campaign 2: BitcoinTalk Translations".

**Comment by AlexeyAnshakov** [comment]
Go through treads on https://bitcointalk.org/index.php?board=238.0
to find Participants links like this one
https://docs.google.com/spreadsheets/d/1iM59i-_j64XpTsguN82_jMajZsdSKKadYK3Ru1e7GWA/edit#gid=0
so you can send invite them to participate in our campaign as well.

**Comment by AlexeyAnshakov** [comment]
Add a signature reward as they did
https://bitcointalk.org/index.php?topic=2153571.0

Weekly Campaign Rates (pre ICO WRG):

Junior Members : 1,000 WRG / week (Equivalent of $40)
Members : 2,000 WRG / week (Equivalent of $80)
Full members : 3,000 WRG / week (Equivalent of 120)
Senior members : 4,000 WRG / week (Equivalent of $160)
Hero members : 5,000 WRG / week (Equivalent of $200)
Legendary members : 6,000 WRG / week (Equivalent of $240)

Logo
https://drive.google.com/open?id=0BwI7_FXP53lIR3RicWZQenhEOXc
Full logo
https://wrioos.com/img/cover1.jpg
Use it for signature banner

**Comment by AlexeyAnshakov** [comment]
Form has been updated. It's very simple now. Reward per like, share, repost and comment.

**Comment by ghost** [comment]
Perfect 

Sent from my iPhone

**Comment by ghost** [comment]
is this ok? I've already edited it a few times. 

Can you send me the final one?

Thanks

**Comment by AlexeyAnshakov** [comment]
I believe we're ok for now.

**Comment by AlexeyAnshakov** [comment]
@Hexah07 please review the google doc and let know if you have ideas how to improve.
