### ISSUE TITLE
Crowdsale Registration · One Time Event

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1258]
We're going to propose an Crowdsale Pre-order Form to find out how many people would like to participate in the Crowdsale. We'll add it to our posts and hub.
Please check the draft and think how to improve it.
https://docs.google.com/forms/d/e/1FAIpQLSfe5bYJYayC_ZwmWgHjea-gij5-2MohY5TaOwHT4QhVU_iVnQ/viewform?usp=sf_link

@jaezed @desireedickerson please help to Waleed.

**Comment by desireedickerson** [comment]
I edited this. Are we providing more information on a follow-up email or on the website? ETH/BTC addresses? Sale end date? Price, etc?

**Comment by AlWaleed84** [comment]
Some links that may help for now, and some for later.. 
-https://rivetzintl.com/sale   (status and token facts)
-https://district0x.io/    (what it does/it's uses)
-https://ico.adshares.net/ (max/min cap, and how to participate)
-https://token.enigma.co/  (countdown & documentation+legal ready)
-...

**Comment by AlexeyAnshakov** [comment]
Form has been updated. The issue will be closed after updating the WP and Bounty campaign links.

**Comment by AlexeyAnshakov** [comment]
Form has been updated. Referral link has been added. Please improve the text.

**Comment by AlexeyAnshakov** [comment]
Referral link has been added. Please improve the text.
We have to collect users for at least 20 mln WGD before Crowdsale start.

**Comment by desireedickerson** [comment]
I can no longer edit the document. Can you share with me so I can edit, please?

**Comment by AlexeyAnshakov** [comment]
Shared

**Comment by desireedickerson** [comment]
I edited it

**Comment by ghost** [comment]
I don't think I have access to this form either

j.

**Comment by AlexeyAnshakov** [comment]
@jaezed please send me your email

**Comment by jaezed** [comment]
jillian.zavitz@gmail.com

j.

**Comment by AlexeyAnshakov** [comment]
https://files.slack.com/files-tmb/T596JK7RN-F7FEEGYS3-8d8b1830f5/registration_1024.jpg
Proofread and improve. We're going to send it as the invitation to linkedin contacts.

**Comment by AlexeyAnshakov** [comment]
Find investors on https://angel.co
Browse tech startups (cryptocurrency and semantic web first of all) and find INVESTORS, contact them and invite to register.

**Comment by AlexeyAnshakov** [comment]
https://github.com/webRunes/WRIO-InternetOS/issues/1250
Especially crunchbase.com/app/search/investors

**Comment by ghost** [comment]
Ok will send edits

**Comment by ghost** [comment]
[EDITED.pdf](https://github.com/webRunes/WRIO-InternetOS/files/1364759/EDITED.pdf)
[Form edited.pdf](https://github.com/webRunes/WRIO-InternetOS/files/1364758/Form.edited.pdf)

**Comment by ghost** [comment]
Hi Alexey 

I added these as PDF with comments please let me know if they arent clear 
Just for look and feel -- the salmon pink is not a good colour -- can we pick a stronger colour

**Comment by AlexeyAnshakov** [comment]
>This is worded ok -- i would just use clickable links instead of writing out the links

Not sure, what do you mean, its are links already.
>Payment minimum is 25 posts

25 shares, likes and etc., not posts
>CLICK HERE to register (make it clickable)

it's an image we can do clickable image by itself only
https://files.slack.com/files-tmb/T596JK7RN-F7FUP7E6S-b1787c90af/registration_1024.jpg

**Comment by ghost** [comment]
Hey alexey 

When I say clickable I mean like a hyperlink 

Like Click here ( and it takes me somewhere) instead of click here http://www.hotmail.com

When I use clickable I use it like that.

**Comment by AlexeyAnshakov** [comment]
since this is an image, we have to show a link so that people at least can insert this link manually if there is no way to click on the image.

**Comment by ghost** [comment]
ok makes sense -- got it :)

**Comment by AlexeyAnshakov** [comment]
We'll try to sell WGD for 100k on https://tokenator.io right before our special round. @AlWaleed84 please contact them and start negotiations.
