### ISSUE TITLE
Publish: WRIO Internet OS. Vision of the Future Internet

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1259]
Please publish on medium and reddit https://docs.google.com/document/d/1VaONNTopFdOKi4D8wiPDXByUNHbhNRztRTgGzH3A8XY/edit after https://github.com/webRunes/WRIO-InternetOS/issues/1256 and https://github.com/webRunes/WRIO-InternetOS/issues/1258 completion. So people can join us after reading

**Comment by AlexeyAnshakov** [comment]
@desireedickerson please proofread the text.

**Comment by AlexeyAnshakov** [comment]
ETA?

**Comment by ghost** [comment]
@AlexeyAnshakov do you want me to have a look at it?

**Comment by AlWaleed84** [comment]
Yes please Jillian.  Some parts need re-writing.  Made some changes to a bit- definitely not enough.

**Comment by ghost** [comment]
Ok sure I'll have a look at this tonight

**Comment by ghost** [comment]
I've ran through it - please let me know if you have other questions

also should there be like chapters or some type of sequencing numbers for each story?

**Comment by AlexeyAnshakov** [comment]
We're going to create a science fiction book with a separate stories but in the one "WRIO OS Universe".

**Comment by ghost** [comment]
Is this ok? are there more sections that need editing?

**Comment by AlexeyAnshakov** [comment]
We're ok for now. We're going to publish more if successful. Comments will be resolved in a few days.

**Comment by ghost** [comment]
Can I use this for the Social Media?

**Comment by AlexeyAnshakov** [comment]
Soon. I'm going to prepare the very first blog post in a day.

**Comment by ghost** [comment]
Ok

**Comment by AlexeyAnshakov** [comment]
We're online! https://webrunes.com/blog/WRIO_Internet_OS._Future_Fragments
Let's see what we can improve and let's publish on social media.

**Comment by AlexeyAnshakov** [comment]
@jaezed please publish on SM our posts https://webrunes.com/blog/. Closed.
