### ISSUE TITLE
Publish: Extract of The Alternative

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1261]
After https://github.com/webRunes/WRIO-InternetOS/issues/1260 completion.

Please do not forget to add #1256 and #1258.

**Comment by ghost** [comment]
Where can i see this?

**Comment by AlexeyAnshakov** [comment]
https://drive.google.com/file/d/0BwI7_FXP53lISnlZeWl6dVQxUjA/view?usp=sharing
