### ISSUE TITLE
Publish: WRIO Internet OS

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1262]
https://docs.google.com/document/d/1kdKoDfp9mT5M4pssJTqvA6sw4zzYQ5HFaN-osu7J-Nk/edit?usp=sharing
After #1152 and #1261 completion.

Please do not forget to add #1256 and #1258.

**Comment by AlexeyAnshakov** [comment]
@jaezed please proofread. Thanks

**Comment by AlexeyAnshakov** [comment]
Sry, removed, we're ok with text

**Comment by AlexeyAnshakov** [comment]
I'm going to publish it soon on https://webrunes.com/blog/

**Comment by AlexeyAnshakov** [comment]
Post uses THX that must be changed on ￠or ø. I'd like to hear your toughts.

**Comment by ghost** [comment]
￠
ᐧ

j.
