### ISSUE TITLE
angel.co contacts

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1264]
Please start adding angel.co contacts: IT investors, semantic web and blockchain enthusiasts. People who might be interested in our ICO, so you will be able to send them invitations after ICO start. I believe we need at least 1000 contacts.

**Comment by ghost** [comment]
Ok I will add this

**Comment by ghost** [comment]
https://docs.google.com/spreadsheets/d/1FpNcYA7tFt3fQNOsNzgZZGIigsomMpGmFTE6kuUb-uU/edit?usp=sharing  

@AlWaleed84 - I've put this together and have added you as an editor if you want you can add some info there -- if we need 1000 + contacts it will make it easy to track
(it's easier than Zoho ;))

**Comment by AlexeyAnshakov** [comment]
Looks reasonable. Thanks.
I believe it's a good point to add Linkedin in the doc as well.

**Comment by AlWaleed84** [comment]
Awesome! Looks good. Thanks Jillian. 

AlWaleed K. AlShehail

**Comment by AlexeyAnshakov** [comment]
I see only 69 linkedin contacts. Please add angel.co as well. @AlWaleed84 please mark in green contacts which you have already added.

**Comment by AlWaleed84** [comment]
**Temporarily**; here's a list of blockchain investors on angel.co
(https://angel.co/blockchains/investors)

**Comment by AlexeyAnshakov** [comment]
The question is, who is connected with us, so that we can send them them an ICO invitation.

**Comment by ghost** [comment]
Ok 

Am working on this list

**Comment by AlexeyAnshakov** [comment]
What progress?

**Comment by ghost** [comment]
I’ve added some lists of entrepreneurs/ investors etc — and am looking to add more influencers 

They are in the form 

From angel there are over 500 people to contact

**Comment by AlexeyAnshakov** [comment]
Find investors on https://angel.co
Browse tech startups (cryptocurrency and semantic web first of all) and find INVESTORS, contact them and invite to register https://github.com/webRunes/WRIO-InternetOS/issues/1258
We won't start Crowdsale until we find 100 potential investors.

**Comment by AlexeyAnshakov** [comment]
Create a text for them, we have to send them https://goo.gl/WGvdiu ASAP.

**Comment by ghost** [comment]
HI Alexey
What do you mean a text? Is there a character limit? what information needs
to be included?
Thanks
ᐧ
j.

**Comment by AlexeyAnshakov** [comment]
You 're free here. But it must be a linkedin message that will prompt a person to become our investor. It must be personal (Hi @name) and contain a WRIO OS description and links: https://goo.gl/4MpwHz Advanced Guide, https://goo.gl/rVcPCV White Paper, https://goo.gl/WGvdiu Crowdsale Registration

**Comment by ghost** [comment]
👌🏻

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by ghost** [comment]
Ongoing --
Waleed said he is constantly searching and adding as well --
ᐧ
j.

**Comment by AlexeyAnshakov** [comment]
There no progress, only 400+ contacts.
I'm also waiting for the text.

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by ghost** [comment]
Hey Alexey - Alwaleed is adding people on angel -- I have a number of
people that I have been adding on linkedin - about 10x day..all blockchain
related
ᐧ
j.

**Comment by AlexeyAnshakov** [comment]
Be ready to use the list soon. How much do we have already?

**Comment by ghost** [comment]
@alwaleed - what is your list please share it with Alexey
ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
@AlWaleed84 provide details and reassign to @RoySasson to complete the task.
