### ISSUE TITLE
Bitcointalk Bounty Campaign

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1266]
Please prepare a Bounty Campaign page like
https://bitcointalk.org/index.php?topic=2051760.0
except "Campaign 2: BitcoinTalk Translations".

**Comment by AlexeyAnshakov** [comment]
https://github.com/webRunes/WRIO-InternetOS/issues/1256

**Comment by AlexeyAnshakov** [comment]
Any progress?

**Comment by AlexeyAnshakov** [comment]
Add bounty card in the description https://files.slack.com/files-tmb/T596JK7RN-F7EKUMMRD-a7a52d5302/promotion_1024.jpg

Add link on the image click for registration form
https://goo.gl/1rFUzQ

**Comment by AlexeyAnshakov** [comment]
Example 
https://bitcointalk.org/index.php?topic=2214619
https://bitcointalk.org/index.php?topic=2201499

**Comment by AlexeyAnshakov** [comment]
Contact ppl on https://docs.google.com/spreadsheets/d/1klEzI5A-brCgNdR2TnjYn5F9_49wh_03vUkxT4v6gLA/edit#gid=181114783 find more in others threads.

**Comment by ghost** [comment]
@AlexeyAnshakov 

I've responded to your concerns in the google doc - 

@AlWaleed84 do you have any comments?

**Comment by AlexeyAnshakov** [comment]
Add stakes for: like on fb, subscribe twitter, star our repository on github https://github.com/webRunes/WRIO-InternetOS/, join telegram and slack.

**Comment by AlexeyAnshakov** [comment]
Could be useful as an example https://docs.google.com/document/d/1pgv54bcUFs9PasgI3EqpQCopSPrYiVRK6ZEXi9H7y0E/edit?usp=sharing

**Comment by AlexeyAnshakov** [comment]
https://matryx.ai/rewards example from Waleed

**Comment by AlexeyAnshakov** [comment]
ETA?

**Comment by AlWaleed84** [comment]
Here's a small plan for community manager, additions and corrections-- let
me know.

I'm expecting a guy to join us through slack tonight, hoping for a post today as well.

**Comment by AlexeyAnshakov** [comment]
Please coordinate and create the Bounty Campaign chapter in the WP https://docs.google.com/document/d/1UM29XhlQ6ZsaWOWhIP5o4_Wh0m8Iy5NtL1-ia7z5aXQ/edit#heading=h.nodwoptkkeru

**Comment by AlexeyAnshakov** [comment]
Please meet @Hexah07, he is going to take care about it.

**Comment by ghost** [comment]
HI there

I am on skype anytime you are available to meet
Thanks

j.

**Comment by AlexeyAnshakov** [comment]
https://github.com/webRunes/WRIO-InternetOS/issues/1357

**Comment by kevinpacayra** [comment]
I am creating some draft for it and I'll show it to you so that missing infos will be given too. Some more time.

**Comment by kevinpacayra** [comment]
I think it is ready but is is okay if the card would be changed just like the date that instead of January 20 it should be this day. And it would be good in English too. Once I post the thread the bounty campaign will be next in line. So what bounty campaign we would open then? Only signature campaign? How about Twitter and Facebook? I will wait reply for both of you. Thanks

1-26-17 00:50 +08:00 UTC

**Comment by AlexeyAnshakov** [comment]
This issue is for Bounty Campaign, it's not even started. Your task is https://github.com/webRunes/WRIO-InternetOS/issues/1357
