### ISSUE TITLE
Advanced Guide proofread

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1271]
Please proofread http://webrunes.com/img/advanced_guide.jpg

**Comment by ghost** [comment]
HI Alexey 
[advanced_guide edits.pdf](https://github.com/webRunes/WRIO-InternetOS/files/1384298/advanced_guide.edits.pdf)

Please see attached.

Thanks!

**Comment by AlexeyAnshakov** [comment]
@jaezed Adv guide has been updated. Just for note: webGold is like Bitcoin and WRG is like BTC. One is the name - another is an abbreviation.

**Comment by ghost** [comment]
Hey alexey 

Yea I get that sometimes it seems weird to have both imo but it’s whatever works- like the first mention in a document yes makes sense to say WebGold (WRG) but then I think just saying WRG is ok because we already know what it is.. 

What do you think?

**Comment by AlexeyAnshakov** [comment]
We use WRG only when we're talking about tokens and webGold when about the project.
