### ISSUE TITLE
The Alternative Extract proofread

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1273]
Please proofread https://alternative.webrunes.org/img/extract.png

**Comment by ghost** [comment]
Working on this as a PDF with comments with edits

**Comment by ghost** [comment]
[extract edit.pdf](https://github.com/webRunes/WRIO-InternetOS/files/1379722/extract.edit.pdf)
Hi Alexey

Please see edit attached.

Some things I have already edited in other content -- thanks!

**Comment by AlexeyAnshakov** [comment]
Thanks, we'll update it soon enough.

**Comment by AlexeyAnshakov** [comment]
Updated. Not all changes were implemented.
