### ISSUE TITLE
ICO Rating

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1276]
I suppose it's a good idea to learn more about
http://icorating.com/
and get their rating.

**Comment by AlexeyAnshakov** [comment]
We also have to submit on http://projecttransparency.org/ to get public confidence and transparency..

**Comment by AlexeyAnshakov** [comment]
https://www.rise.global/blockchain-100

**Comment by AlexeyAnshakov** [comment]
https://icobench.com
https://icobazaar.com
https://foxico.io
https://www.trackico.io
https://icoholder.com
https://www.icocountdown.com
https://preicoreview.com
https://icomarks.com
https://www.icoranker.com
https://www.cryptocompare.com
https://cryptorated.com/
https://tokentops.com/
https://icotop.io/
https://foundico.com
please find more

**Comment by AlexeyAnshakov** [comment]
https://www.trackico.io/
https://icoholder.com

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by AlexeyAnshakov** [comment]
https://cryptorated.com/

**Comment by AlexeyAnshakov** [comment]
https://www.icoalert.com

**Comment by AlexeyAnshakov** [comment]
Additional link from @Hexah07 https://bitcointalk.org/index.php?topic=2938434.0

**Comment by AlexeyAnshakov** [comment]
@RoySasson please proceed.

**Comment by RoySasson** [comment]
Will work on that 

----- הודעה מקורית -----
מאת: "Alexey Anshakov" <notifications@github.com>
נשלח: ‎03/‎05/‎2018 20:54
אל: "webRunes/WRIO-InternetOS" <WRIO-InternetOS@noreply.github.com>
עותק: "Roy Sasson" <roeysa@gmail.com>; "Mention" <mention@noreply.github.com>
נושא: Re: [webRunes/WRIO-InternetOS] ICO Rating (#1276)

@RoySasson please proceed.

**Comment by AlexeyAnshakov** [comment]
foxico.com
ratedicomarks.com
