### ISSUE TITLE
Press

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1277]
We must be published on as much as possible resources like at
https://aeron.aero/#news
https://confedial.com
https://globcoin.io/press.html
https://www.cryptoimprovementfund.io/the-press/
https://icos.icobox.io/media
https://cryptocynews.com
https://en.bitnovosti.com
https://ico-digest.com/
http://www.the-blockchain.com/
http://tokentalk.io
http://bitcoinist.com/
http://EthereumWorldNews.com
Perhaps http://prdpressreleasedistribution.com/
Prepare a list.
Find more on the websites listed in the projects https://docs.google.com/spreadsheets/d/1VdRMFENPzjL2V-vZhcc_aa5-ysf243t5vXlxC2b054g/edit#gid=0
Services to find journalists' contact
https://www.hey.press/
https://justreachout.io/
https://www.linkedin.com/in/blockchain-magazine-373690119 they're ready to publish our story for free.
Use https://blockstack.org/press to contact press. If they wrote about them, they probably will write about us.

Free profile resources where to place the information about your pre-ICO:
Icorating.
Icoalert.
IcoTracker.
CoinsCat.
Tokendata.
Hubcoin.
FoundIco.
Coinhills.
Icobench.
ICOAdvert.
Icolighthouse.
Icolert.
Foxico.
ICO Pro.
Ico holder.
ICORanker.
Trackico.

**Comment by AlexeyAnshakov** [comment]
https://www.cryptoimprovementfund.io/the-press/

**Comment by AlexeyAnshakov** [comment]
https://icos.icobox.io/media

**Comment by AlexeyAnshakov** [comment]
Find more on the websites listed in the projects https://docs.google.com/spreadsheets/d/1VdRMFENPzjL2V-vZhcc_aa5-ysf243t5vXlxC2b054g/edit#gid=0

**Comment by AlexeyAnshakov** [comment]
Perhaps http://prdpressreleasedistribution.com/

**Comment by ghost** [comment]
Hi Alexey - I've been looking at PR sites - there are some that are free -
the CryptoCurrency ones cost money -
Is there a budget?
ᐧ
j.

**Comment by AlexeyAnshakov** [comment]
We are going to use free at first but after collecting some money will use the rest from the list.

**Comment by AlexeyAnshakov** [comment]
https://www.linkedin.com/in/blockchain-magazine-373690119

**Comment by AlexeyAnshakov** [comment]
Services to find journalists' contact
https://www.hey.press/
https://justreachout.io/

**Comment by AlexeyAnshakov** [comment]
cryptocynews.com

**Comment by AlexeyAnshakov** [comment]
https://en.bitnovosti.com

**Comment by ghost** [comment]
What frequency of articles and press releases are you projecting to
release?

What is the budget? - most of these sites for a sponsored article is around
$300-$500

I have seen that money put to better use though through banner ads..

What are you thoughts?
ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
Let's start from a free services. We have to contact through the websites form https://github.com/webRunes/WRIO-InternetOS/issues/1245 and twitter. After collecting some $ we'll pay for the premium services. P.S. Banners are useless and a lot of ppl using adsblockers.

**Comment by AlexeyAnshakov** [comment]
Use https://blockstack.org/press to contact press. If they wrote about them, they probably will write about us.

**Comment by AlexeyAnshakov** [comment]
EthereumWorldNews.com

**Comment by AlexeyAnshakov** [comment]
- Free profile resources where to place the information about your pre-ICO:

Icorating.

Icoalert.

IcoTracker.

CoinsCat.

Tokendata.

Hubcoin.

FoundIco.

Coinhills.

Icobench.
