### ISSUE TITLE
Bloggers

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1278]
Find at least 50 crypto-bloggers who're interested in cryptocurrencies, semantic web and cryptopunks ideas. For theirs posts with ref link https://docs.google.com/forms/d/e/1FAIpQLSfe5bYJYayC_ZwmWgHjea-gij5-2MohY5TaOwHT4QhVU_iVnQ/viewform?usp=pp_url&entry.1977168709=your_email@domain.com we will pay 5%.

**Comment by AlexeyAnshakov** [comment]
Also contact json-ld community https://json-ld.org/ (Mailing List, IRC etc.).

**Comment by AlexeyAnshakov** [comment]
Please find bloggers like https://medium.com/@wmougayar

**Comment by AlexeyAnshakov** [comment]
We have to contact and propose our info to post
https://toppub.xyz/
like Hackernoon, easy to post and have more readers than websites like The Next Web.

**Comment by ghost** [comment]
ok
ᐧ

j.

**Comment by AlWaleed84** [comment]
Got it. 


AlWaleed K. AlShehail

**Comment by AlexeyAnshakov** [comment]
An example which you can use to demo WRIO OS hub https://hhn.wr.io to attract first bloggers.
