### ISSUE TITLE
Intro (Hi-Tech style)

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1279]
Prepare:
- video script (ready for discussion)
- video (in progress)
- audio

**Comment by AlexeyAnshakov** [comment]
Script https://docs.google.com/document/d/1XaARfqxqJCv1SCV7A0Ju8FL-15lbWWo7Z3bfMQwiSuo/edit?usp=sharing
Video in progress.

**Comment by AlexeyAnshakov** [comment]
@jaezed please create a voice track for the intro (wav or mp3/320kbps), text:
Information. Information rules the world. The number of Internet users is nearing 4 billion, while generated information doubles every 18 months. With the advent of the Internet of Things and the explosive growth in the number of connected smart devices, data generation has increased drastically, and thus emerged the critical need for automatic processing of Big Data.
This requires a semantic platform that can unite the web of machines and users. The key for this unification is a machine-readable data format that can enable automatic data processing and is capable of paving the way for a user-centric Web 3.0.
In Web 3.0 users receive screened information automatically based on their interests. Web 3.0 websites are a set of cross-domain machine-readable pages that can exchange data without API and any restrictions.
Pages contain pure data and are processed in the read-only mode, which ensures secure browsing.
Pages metadata is registered in the blockchain, which is also used to store user profiles with the interest matrix. Correlation of metadata with the interest matrix enables automatic distribution of content and creation of predictive search engines and services.
All user actions and browsing are performed through a personal WRIO Internet OS web dashboard.
WRIO Internet OS is a blockchain-powered user-centric Web 3.0 platform, enabling a next-generation browsing experience!

**Comment by AlexeyAnshakov** [comment]
ETA?

**Comment by ghost** [comment]
https://drive.google.com/open?id=1005MNKde8tuw9BNRezwDRphKx4T-TuHk
ᐧ
j.

**Comment by AlexeyAnshakov** [comment]
Ok, thanks.

**Comment by AlexeyAnshakov** [comment]
Text has been updated. But no need to upload the updated version yet.

**Comment by ghost** [comment]
Ok lmk when

**Comment by AlexeyAnshakov** [comment]
Script text v2:
Information is everything. The number of Internet users is nearing 4 billion, while generated information doubles every 18 months.
With the advent of the Internet of Things there are 23 bln connected devices in the world and their number doubles every 36 months.
Global Internet traffic in 2020 will be equivalent to 100 times the volume of the entire global Internet in 2005.
Today’s ‘Web 2.0’ is centralized and full of dangers and restrictions, while users have to dig up information on their own.
It will require a platform that will unite the web of machines and users. The key for this unification will be a machine-readable data format that enables an automatic data processing and paves the way for a user-centric Web 3.0, where users receive screened information automatically based on their interests.
Web 3.0 websites are a set of cross-domain machine-readable pages that can exchange data without API and restrictions. Pages contain pure data and are processed in the read-only mode, which ensures constant secure browsing.
Content metadata is registered on the blockchain, which is also used to store user profiles with the interest matrix.
Utilizing metadata along with the interest matrix enables automatic distribution of content and creation of predictive search engines and services.
Functions and interactivity are provided through cloud and distributed applications while all user actions and browsing are performed through a personal WRIO Internet OS web dashboard.
WRIO Internet OS is a blockchain-powered user-centric Web 3.0 platform, enabling a next-generation browsing experience!

**Comment by AlexeyAnshakov** [comment]
If no comments, please create a new voice track, more powerful and close to https://www.youtube.com/watch?v=r3QynmJ3yoM.

**Comment by ghost** [comment]
Ok got it

**Comment by AlexeyAnshakov** [comment]
This text part "It will require a platform that will unite the web of machines and users. The key for this unification will be a machine-readable data format. Automatic processing of data will pave the way for a user-centric Web 3.0." isn't consistent, will be updated.

**Comment by AlexeyAnshakov** [comment]
The text is ready.

**Comment by AlexeyAnshakov** [comment]
@jaezed you used the old text for the part "It will require a platform that will unite the web of machines and users. The key for this unification will be a machine-readable data format that enables an automatic data processing and paves the way for a user-centric Web 3.0, where users receive screened information automatically based on their interests."

**Comment by AlexeyAnshakov** [comment]
@jaezed you used the old text for the part "It will require a platform that will unite the web of machines and users. The key for this unification will be a machine-readable data format that enables an automatic data processing and paves the way for a user-centric Web 3.0, where users receive screened information automatically based on their interests.". Please use the text in this issue. No need to record the whole text again, we need this part only.

**Comment by AlexeyAnshakov** [comment]
WRIO Internet OS (last two sentences) must be pronaunced as it was at https://www.youtube.com/watch?v=ntQulTFH7hk

**Comment by AlexeyAnshakov** [comment]
WRIO Internet OS (last two sentences) must be pronaunced as it was at https://www.youtube.com/watch?v=ntQulTFH7hk and please add more optimistic and power to the last sentence as it has "!".

**Comment by ghost** [comment]
Ok

**Comment by AlexeyAnshakov** [comment]
ETA?

**Comment by ghost** [comment]
I will do this tonight - sorry it was really loud in my office today
ᐧ
j.

**Comment by ghost** [comment]
https://drive.google.com/open?id=1E1g95XL15jPiV7Rw52j_LQ0Ol_N95W57

I did a few recordings on there so it may be out of order at the end --

The text wasn't updated on the google sheet so I'm confused which one you wanted me to use -- i recorded both..

**Comment by AlexeyAnshakov** [comment]
Next time please use info in the github issue only, docs could be in progress.

**Comment by AlexeyAnshakov** [comment]
>WRIO Internet OS (last two sentences) must be pronaunced as it was at https://www.youtube.com/watch?v=ntQulTFH7hk and please add more optimistic and power to the last sentence as it has "!".

**Comment by ghost** [comment]
Hi alexey sorry what part are you talking about in the video can you send me the frame time so I can get it right :) thanks

**Comment by AlexeyAnshakov** [comment]
It's going through whole video starting from https://youtu.be/ntQulTFH7hk?list=WL&t=9

**Comment by ghost** [comment]
https://drive.google.com/open?id=1z0gXKaO49blSMgu6DbKgr95ny02UjAbQ

**Comment by AlexeyAnshakov** [comment]
Release candidate https://youtu.be/K--L3fVDCXA

**Comment by ghost** [comment]
That’s neat 
I dig it —

**Comment by AlexeyAnshakov** [comment]
@jaezed if no comments, please create the final audio track and we're ready to finish the task.
Please adhere to the intonation in RC version.

**Comment by ghost** [comment]
Alwaleed is doing it — 

Lmk if I need to redo it or if you could work with it Waleed

**Comment by AlexeyAnshakov** [comment]
Ok, let's wait his comments.

**Comment by AlWaleed84** [comment]
Hey Jillian— Are you making a newer read through?  What is the one for the functions for?


AlWaleed K. AlShehail

**Comment by ghost** [comment]
I wasn't planning on it -- its just i said WRIO incorrectly so i rerecorded
the last two sentences..
ᐧ

j.

**Comment by AlWaleed84** [comment]
Hey.. So I think this sounds better and more presentable, and it's ready to
use.

Layered vocals, and some cyberpunk backdrop-  made on logic pro.

file:///Users/alwaleed/Music/iTunes/iTunes%20Media/Music/Waleed/Unknown%20Album/WRIO%20Video-%20STRK_.m4a

It's attached if you wanna download.

AlWaleed K. AlShehail

**Comment by ghost** [comment]
Wait its not attached :( 🙌🏻🙌🏻

**Comment by AlexeyAnshakov** [comment]
[WRIO Video- STRK_.zip](https://github.com/webRunes/WRIO-InternetOS/files/1503003/WRIO.Video-.STRK_.zip)

**Comment by AlexeyAnshakov** [comment]
It's could be ok, but:
- wrong WRIO OS pronunciation. It must sound as [:rio os]
- too plain, @jaezed did a good job and I like her version much more
- no need for the background sounds, it's interference with background music we have
- perhaps sound effect is a "hi-tech", but it interferes with the perception of information

**Comment by AlWaleed84** [comment]
We have many videos calling it W.R.I.O.. what changed? 

Also, Jillian’s enthusiasm is great on the track, however this sounds similar to the ‘blackout’ video so it has a cool factor—  So I don’t agree. 

Anyways my opinion is, unless you guys are going to do it professionally— I suggest avoid doing it now. 


AlWaleed K. AlShehail

**Comment by AlexeyAnshakov** [comment]
We have only the one and first video with W.R.I.O. I mentioned a several times in the issue that started from https://www.youtube.com/watch?v=ntQulTFH7hk we're using [:rio os].

**Comment by ghost** [comment]
https://drive.google.com/file/d/1mdU9SS41bdcZT317CFAeX8gig2ba8Ju2/view?usp=sharing

Ok its V.3 

Let me know -- I tried to do it with different recording devices -- 

If it's still not good - I can try on Wednesday to do it with a microphone and AMP sorta thing at a professional place.

**Comment by AlexeyAnshakov** [comment]
Thanks. I think it's ok.

**Comment by AlexeyAnshakov** [comment]
https://www.youtube.com/watch?v=oXECsbliAnI
In a few days it's going to be listed.

**Comment by ghost** [comment]
That’s pretty alright :)

**Comment by AlexeyAnshakov** [comment]
In fact on good stereo system sound is not very good. @AlWaleed84 i've uploaded audio, you can play with it to make it closer to your prev clean version but without background.
[audio.zip](https://github.com/webRunes/WRIO-InternetOS/files/1507858/audio.zip)

**Comment by AlWaleed84** [comment]
Ok— I’ll give it a try and upload in a few hours. 



AlWaleed K. AlShehail

**Comment by AlexeyAnshakov** [comment]
For sure you can use an original source, perhaps it a better start point.

**Comment by AlWaleed84** [comment]
Will upload AM tomorrow. 


AlWaleed K. AlShehail

**Comment by AlWaleed84** [comment]
Ok, so this is Jillian on steroids :)

**Comment by AlexeyAnshakov** [comment]
No attachment.

**Comment by AlWaleed84** [comment]
That's weird.  I can see it uploaded.  Try this.

**Comment by AlWaleed84** [comment]
Using G-drive...  check this instead.

​
 WRIO-Jill.m4a
<https://drive.google.com/file/d/1OwHAV93SKWlFK629hhK9LwGPVlTGpXms/view?usp=drive_web>
​

**Comment by AlexeyAnshakov** [comment]
Good job! I believe we're good now. I made the voice track a little bit deeper and the intro is live at  https://www.youtube.com/watch?v=q7WevBb8JeQ
