### ISSUE TITLE
Message template for the survey "The Future of the Web"

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1294]
@jaezed please prepare a message template you'll send to potential investors. To increase the chance to attract investors, every message must be personal. No need to dig a lot, just a few words why we wrote to him/her: "we found out that you're interested in [cryptocurrencies, cryptoeconomy, political freedom and so on. Based on info from the social media profile]", that's why we believe you'll be interested... etc.

We do not have to ask for money, we need to attract people, they will decide to participate by themselves if the like the project. To attract them please ask questions and feedback and include something like: "We'd gladly pay you 10-500 WRG for feedback at [links to intro, hub, and WP https://wrioos.com/white_paper (not ready yet)]".

**Comment by AlexeyAnshakov** [comment]
We should add a ref link as a special bonus to contact. Text must contain a simple project description and benefits: why it's a good idea to invest -- machine-readable and predictable next google+facebook (just an idea, personaly I'd like to avoid such comparison)

**Comment by AlexeyAnshakov** [comment]
One of the approach I see is create a poll instead of asking for investment (it always meets with opposition in the heads), e.x.:
```
We found out that you're interested in [cryptocurrencies, cryptoeconomy, political freedom and so on. Based on info from the social media profile], that's why we believe you'll be interested in the poll:
1. Do you agree with the statement: We are rushing into the era of Internet of Things and Big Data where an automated processing of data will be a must
... and so on.
Participant who filled up email field will get a interesting poll results on email.
```
After answers the respondent must come to a logical conclusion of the need for the project.

**Comment by AlWaleed84** [comment]
You mean where one side leads to investing in the project, and the other doesn’t, correct? 


AlWaleed K. AlShehail

**Comment by ghost** [comment]
Maybe both lead to investing would be better

**Comment by AlexeyAnshakov** [comment]
Poll name: "The Future of the Web".
Poll must be separated on sections like: Security, Privacy, Net neutrality (+ censorship and blocking). Questions example, please improve and create the first version, use Adv. guide to create questions:
- Next web generation must be:
[checkbox] Machine-readable (description)
[checkbox] Blockchain-powered (description)
...
[text field] Your option

- Statement: Serch engines will be always popular
[checkbox] Agree. People will always search in the same manner
[checkbox] Disagree. We'll see something else

- Statement: Social media will be always popular
[checkbox] Agree. (add text)
[checkbox] Disagree. They're already losing popularity.

- Statement: Our privacy is in danger
[checkbox] Agree. (add text)
[checkbox] Disagree. With social media help goverment knows about me everything and that's ok

Perhaps (or maybe not) we should add points for answers, the more points the higher % crowdsale discount.

Find articles how to create a poll. Perhaps I'll create images for every section a bit later.
Poll will be published on wrioos.com and we've to create a thread on reddit.

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by ghost** [comment]
How did you want to do this? - The only poll i can think of doing is on google - but not sure if these are too many questions for people.

I almost think that investors will either invest or they wont and wont want to go through a poll

**Comment by AlexeyAnshakov** [comment]
The idea is to attract point of interest by asking to fill out an interesting poll where responders will find out about probplems, agree with them, find answers and our project as a solution.
Well, it seems that I should do it myself a bit later.

**Comment by AlexeyAnshakov** [comment]
We're going to propose a webGold reward for the survey.

**Comment by ghost** [comment]
what is the reward?
ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
500 WRG, i'm going to create a colorful reward card soon.

**Comment by AlexeyAnshakov** [comment]
No progress. Apparently I have to do this myself as well.

**Comment by AlexeyAnshakov** [comment]
The survey is ready https://goo.gl/BkLz7K
A card is coming. ETA: after bitcointalk thread.

**Comment by ghost** [comment]
great
ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
Please prepare the template, what we have to send to contact to be successful.

**Comment by ghost** [comment]
Hello <insert name>,

Did you know there is a way to have an internet tailored exactly to you and
your your interests, without irrelevant advertising?

Web 3.0 is the answer and the future.

Find out more by completing the survey.  At the end you will receive 500
WebGold tokens as a "Thank You".

Click here to claim your Prize.


Sincerely,

WRIOOS Team



Hello <insert name>.

Imagine an automatic data processing that will enable tuning up browsing
experience based on the needs and interests of each individual user.

Find out more here and claim your prize at the end.

Sincerely,

WRIOOS Team



Hello <insert name>,

We are paving the way for a user-centric Web 3.0 with predictive services
and search engines of a new generation.

Interested in finding out more?

CLICK HERE and claim your 500 WebGold prize at the end.

Sincerely,

WRIOOS TEAM


ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
webRunes Team. @AlWaleed84 please coordinate with Jillian to prepare the text.

**Comment by AlexeyAnshakov** [comment]
It's done. I'm going to create a new issue for next stage: sending.
