### ISSUE TITLE
Crediting

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1295]
We have to do the same
https://bitcointalk.org/index.php?topic=2272412.80
2,500 maximum participants
100 WRG for each participant

Will start soon.

**Comment by ghost** [comment]
Airdrops are after the tokens are put on the exchanges typically after the ico is over

**Comment by AlexeyAnshakov** [comment]
Find more participants' links of other projects to invite ppl https://docs.google.com/spreadsheets/d/15xgwPz5N-k9bTPWkJfg4L7sY6uBoKQprdwx0A9EqDR4/edit#gid=1294312542

**Comment by AlexeyAnshakov** [comment]
That's right, airdrop's reward will be send after ICO.

**Comment by AlWaleed84** [comment]
The term ‘Airdrop’ will have people think it’s free— I suggest we use crediting instead. 

Cryptocurrency ‘Airdrop’ is defined like this by bitcointalk in 2016; “free giveaway of pre-mined coins.” 


AlWaleed K. AlShehail

**Comment by AlexeyAnshakov** [comment]
Ok, changed.

**Comment by ghost** [comment]
But no giveaway threads are allowed

PLUS we need to come up with some small task for this airdrop to happen.


ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
> small task 

the same as https://docs.google.com/forms/d/e/1FAIpQLScPY6nMVnLXBNNyILA7RZ-oBH3Mt3UTOlSxkk0FQPaQ5vTqiw/viewform

**Comment by ghost** [comment]
Ok - so this is for at the end of the ICO - 

@alexey - is there a feature in GitHUB that is a timeline / milestone tracker?

**Comment by AlexeyAnshakov** [comment]
https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests/

**Comment by ghost** [comment]
Thanks
