### ISSUE TITLE
wrioos.com hub text proofreading

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1296]
@jaezed https://docs.google.com/document/d/1XaARfqxqJCv1SCV7A0Ju8FL-15lbWWo7Z3bfMQwiSuo/edit?usp=sharing please proofread.
Main question is it ok to use creditor instead of donator:
```
Though the initial cost of CCC coins is not high (see below), in case of a good many of CCC creditors the amounts become sufficiently large to support authors.
```
Creditor is someone who give money  in order to generate income.

**Comment by AlexeyAnshakov** [comment]
ETA?

**Comment by ghost** [comment]
Hi Alexey

Sorry I was unsure of what you needed me to go through here - but I went
through it all - Please let me know if there are further questions.

or Edits
ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
>Main question is it ok to use creditor instead of donator:

**Comment by ghost** [comment]
yes its ok

**Comment by AlexeyAnshakov** [comment]
If there no additional ideas let's simplify Cypher Credit Coin (CCC) to Credits (CRD).

**Comment by ghost** [comment]
Ok

**Comment by AlexeyAnshakov** [comment]
wrioos.com is ready.
