### ISSUE TITLE
FB, Linkedin, Twitter pages

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1297]
@jaezed now you have an access to our FB, Linkedin, Twitter pages. Please publish here updates and thoughts what have to be done with fb.

**Comment by ghost** [comment]
Hi ALexey 

I don't have access to LinkedIN - I have requested it

**Comment by ghost** [comment]
I also don't have access to Twitter 


Only to Facebook 

Where can I find a folder with images etc?

Thanks

**Comment by AlexeyAnshakov** [comment]
Twitter:
```
icochick @icochick
Contributor
Can Tweet as @webRunes
```
Try to send a tweet. Maybe through https://tweetdeck.twitter.com

**Comment by AlexeyAnshakov** [comment]
>Where can I find a folder with images etc?

https://github.com/WRIO-Hubs/webrunes.com-WRIO-Hub/tree/gh-pages/img and WP.
Let me know if you need smt. more.

**Comment by ghost** [comment]
Thanks you

**Comment by AlexeyAnshakov** [comment]
@jaezed you were added as admin to angel.co as well. Please inprove text according info on wrioos.com

**Comment by AlexeyAnshakov** [comment]
Please double check we have actual info for all SM pages.
Check https://github.com/webRunes/WRIO-InternetOS/issues/1359 for additional details.

**Comment by ghost** [comment]
All Linked In Twitter and FB pages are updated - Twitter has a tweet going
our daily LinkedIn weekly and FB often as well
ᐧ

j.
