### ISSUE TITLE
Reddit

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1300]
@AlWaleed84 please find and join subreddits like this
https://www.reddit.com/r/icocrypto/
we're going to publish right before ICO.

**Comment by AlexeyAnshakov** [comment]
https://github.com/webRunes/WRIO-InternetOS/issues/1245

**Comment by ghost** [comment]
How will we be doing this? through our own private reddit accounts or the Wrio one?

Have I been added as an admin to our reddit?

**Comment by AlexeyAnshakov** [comment]
@AlWaleed84 please help with this one.

**Comment by AlexeyAnshakov** [comment]
Reddit will be added to Bounty
Reddit/Blog/Article bounty: 15% WGD

**Comment by ghost** [comment]
ok
ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
Reddit campaign added to the Bounty Campaign.
