### ISSUE TITLE
One-pager proofreading

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1334]
Please proofread the text https://docs.google.com/document/d/1XaARfqxqJCv1SCV7A0Ju8FL-15lbWWo7Z3bfMQwiSuo/edit#heading=h.w5tl6mj066h4

**Comment by ghost** [comment]
Ok I will do this this evening

**Comment by AlexeyAnshakov** [comment]
Published on Slack.
