### ISSUE TITLE
Searching for investors

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1356]
https://crunchbase.com/app/search/investors

https://github.com/webRunes/WRIO-InternetOS/issues/1250

**Comment by AlexeyAnshakov** [comment]
https://github.com/webRunes/WRIO-InternetOS/issues/1250

**Comment by AlexeyAnshakov** [comment]
@jaezed please prepare a list (contact them), so we can reach them out a bit later.

**Comment by ghost** [comment]
What type of investor are you looking for there are over 90,000 there
ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
First of all related to: the Semantic web, linked data, web3, blockchain, cryptocurrency, DAO.

**Comment by ghost** [comment]
ok
ᐧ

j.
