### ISSUE TITLE
Bitcointalks threads

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1357]
Please start to edit https://docs.google.com/document/d/1f1DaL0K-rnYz6-_eWlplV85Sl8JkqLWHYMoB6WOPB14/edit?usp=sharing

Use https://docs.google.com/document/d/1XaARfqxqJCv1SCV7A0Ju8FL-15lbWWo7Z3bfMQwiSuo/edit#heading=h.w5tl6mj066h4

https://github.com/webRunes/WRIO-InternetOS/issues/1266

Overdue: 4 days

**Comment by kevinpacayra** [comment]
### Bitcointalk ANN thread - [DONE]
ETA: [18-Jan-2018]
UPD: [19-Jan-2018]. The first version received comments and now needs further improvements.
UPD: [25-Jan-2018]. Done by Alexey Anshakov.
The ANN card is ready https://webrunes.com/img/cards/ann_thread.jpg
UPD: [29-Jan-2018]. Must be published on 29 Jan.

Preparing an ANN thread like this one:
https://bitcointalk.org/index.php?topic=2036653.0

Overdue: 4 days

### Bounty Campaign - [DONE]
ETA: 28-Jan-2018
Upd: 29-Jan-2018
Bounty thread are ready but there are need for slight editing when be posted on Bitcointalk.
ETA: 30-Jan-2018
UPD: 31-Jan-2018
Completion of bounty thread. Just forms and spreadsheet then it will be posted on Bitcointalk.

https://docs.google.com/document/d/1f1DaL0K-rnYz6-_eWlplV85Sl8JkqLWHYMoB6WOPB14/edit?ts=5a631587#heading=h.ahiv4bnagnga

**Comment by AlexeyAnshakov** [comment]
Use https://docs.google.com/document/d/1XaARfqxqJCv1SCV7A0Ju8FL-15lbWWo7Z3bfMQwiSuo/edit#heading=h.w5tl6mj066h4

**Comment by AlexeyAnshakov** [comment]
The ANN card is ready webrunes.com/img/cards/ann_thread.jpg

**Comment by AlexeyAnshakov** [comment]
Bitcointalk ANN thread is done

**Comment by AlexeyAnshakov** [comment]
Signature Campaign codes are ready https://docs.google.com/document/d/1f1DaL0K-rnYz6-_eWlplV85Sl8JkqLWHYMoB6WOPB14/edit?ts=5a631587#heading=h.ahiv4bnagnga

**Comment by Hexah07** [comment]
ETA: 28-Jan-2018
Upd: 29-Jan-2018
Bounty thread are ready but there are need for slight editing when be posted on Bitcointalk.

https://docs.google.com/document/d/1f1DaL0K-rnYz6-_eWlplV85Sl8JkqLWHYMoB6WOPB14/edit?ts=5a631587#heading=h.ahiv4bnagnga

**Comment by AlexeyAnshakov** [comment]
Your ETA moved to the proper comment.
Please check out my comments in the doc file.

**Comment by Hexah07** [comment]
ETA: 30-Jan-2018
UPD: 31-Jan-2018
Completion of bounty thread. Just forms and spreadsheet then it will be posted on bitcointalk.
