### ISSUE TITLE
SM pages description

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1359]
Please update/prepare a description for all our pages
https://angel.co/webrunes
https://www.youtube.com/c/Webrunes
https://twitter.com/webRunes
https://www.facebook.com/webRunes

on https://docs.google.com/document/d/1XaARfqxqJCv1SCV7A0Ju8FL-15lbWWo7Z3bfMQwiSuo/edit

**Comment by ghost** [comment]
I am waiting for the bitcoin talk thread links in order to post on these
platforms --

please let me know what they are so I can get these out today

Thanks
ᐧ

j.

**Comment by ghost** [comment]
What is the Youtube login +
Do you have a list of all the logins somewhere just for reference?

Thanks
ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
Youtube channel
http://youtube.com/c/webRunes
Please create descriptions for all SM in the doc file.
