### ISSUE TITLE
Bitcointalk promotion

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1366]
I'll find contractors who'll contact people from others bounty campaigns and invite them to be involved in our Bounty Campaign as well.
I'll create a list of docs files like this one https://docs.google.com/spreadsheets/d/1sfGJvG0CDtz99GQhCw8TRiSPbqNq7KphrhRkhhFVrb0/edit?usp=sharing
@AlWaleed84 @jaezed please prepare an invitation template where contractors will add a name only. This template has to include the https://webrunes.com/img/cards/bounty_thread.jpg

**Comment by AlexeyAnshakov** [comment]
ETA for the template?

**Comment by AlexeyAnshakov** [comment]
Please create a pin message for the telegram group.

**Comment by AlexeyAnshakov** [comment]
@jaezed it's easy to find docs url https://www.google.pl/search?hl=en&as_q=bounty&as_epq=&as_oq=&as_eq=&as_nlo=&as_nhi=&lr=&cr=&as_qdr=all&as_sitesearch=bitcointalk.org&as_occt=any&safe=images&as_filetype=&as_rights= please open one by one and find spreadsheets url. Copy contacts to a proper tab in the https://docs.google.com/spreadsheets/d/1sfGJvG0CDtz99GQhCw8TRiSPbqNq7KphrhRkhhFVrb0/edit?usp=sharing. We need about 20 docs files in total to get 20,000 contacts. You may change columns' names in case docs files have another format.

**Comment by AlexeyAnshakov** [comment]
@jaezed additional url of contacts https://bitcointalk.org/index.php?topic=2704656.0
https://bitcointalk.org/index.php?topic=2833315.0

**Comment by ghost** [comment]
Hi Alexey

There are over in total I'd say 10,000 contacts spread throughout the list -
The clean one is called EDITED

I will work on a second list for contacting as well.

Thanks

j.

**Comment by AlexeyAnshakov** [comment]
@AlWaleed84, a bit later we should consider a prev offer and start from $500 option, what do you think?
“Option#1 (one off data purchase)

$500 for 2,500 records delivered in csv format
$1,000 for 10,000 records delivered in csv format
$7,500 for 100,000 records delivered in csv format
$15,000 for 350,000 records delivered in csv format

We can also customize the data set according to requirements you provide, such as records with mandatory fields populated (i.e. must have mobile). 

Option#2 (30 day audience rental)”

**Comment by AlexeyAnshakov** [comment]
More contacts https://docs.google.com/spreadsheets/d/1zz1AgQ-UJP1AzSiT0BmTx6d4sx8lTrstNaHsZuIx9eA/edit#gid=99988622
if need be

**Comment by ghost** [comment]
Hi There

How are we going to be contacting all of these people?

ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
We're going to start a special promoting campaign (thread). Plus, we'll send an invitation to our 600+ telegram users.

**Comment by ghost** [comment]
Ok

**Comment by AlexeyAnshakov** [comment]
Jillian, we've a good start today - 10 people joined us as ambassadors (only one of them brought 7 new investors). I believe we'll have much more after weekends. In this case we have to add more contacts.

**Comment by ghost** [comment]
Ok

**Comment by AlexeyAnshakov** [comment]
Ambassadors are doing well. I'll proceed. Closed.
