### ISSUE TITLE
Change "Donated 0 THX" to "Credited 0 CRD"

### ISSUE THREAD

**Issue by spirinvladimir** [webRunes/WRIO-InternetOS#1370]
Screen shot with problem:
<img width="656" alt="screen shot 2018-02-16 at 10 22 53 am" src="https://user-images.githubusercontent.com/2780401/36313864-6bb2e78a-1309-11e8-9aef-bf4876f08ad9.png">
Should be "Credited 0 CRD"

**Comment by AlexeyAnshakov** [comment]
I suppose it's a https://github.com/webRunes/Pinger-WRIO-App issue.

**Comment by spirinvladimir** [comment]
Fixed 
<img width="620" alt="screen shot 2018-02-16 at 2 26 54 pm" src="https://user-images.githubusercontent.com/2780401/36322920-894943e0-1325-11e8-830a-329835033b3d.png">
