### ISSUE TITLE
localhost instruction. Reward 10 USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#138]
Create a step-by-step wiki instructions for WRIO deployment on localhost

> https://github.com/webRunes/WRIO-InternetOS/wiki/Deploy-on-localhost

**Comment by AlexeyAnshakov** [comment]
Добавить/отредактировать по-русски инструкцию, перевод я добавлю позже.

**Comment by spirinvladimir** [comment]
```
git clone --recursive https://github.com/spirinvladimir/WRIO-dev.git
cd WRIO-dev
npm i
npm start
```

http://localhost:3000/

**Comment by AlexeyAnshakov** [comment]
а почему указан не webRunes репозиторий?

**Comment by spirinvladimir** [comment]
![selection_003](https://cloud.githubusercontent.com/assets/2780401/7907471/41516108-0842-11e5-85f8-ea6c118aa2f6.png)
