### ISSUE TITLE
Tokenator

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1402]
https://tokenator.io/en @AlWaleed84 please take a look with @jaezed and let me know your ideas how we can use it,

**Comment by ghost** [comment]
This is to be used for token distribution?
I'm confused


ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
Please dig in, seems we can try to sell our tokens here.

**Comment by AlexeyAnshakov** [comment]
@AlWaleed84 please contact them as well.

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by AlexeyAnshakov** [comment]
@RoySasson please contact them and find out the details. Dig them a bit to learn more how we can use them and if it worth it.
