### ISSUE TITLE
The Future of the Web · Survey. Stage: sending to Linkedin and angel.co contacts

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1427]
Please start to send to contact you have prepared.
I hope each of you can send at least 50 messages to Linkedin and 50 to angel.co per day. Let me know if I'm too optimistic.
Don't forget to add Event Card as an attachment.

Message template:
```
Hi <insert name>,
Considering your profile, you and other forward-looking Internet users are invited to share your vision of the web future
https://docs.google.com/forms/d/e/1FAIpQLSdXFAEP7fZB2QSt0vWbtCxp35e1L-Ue7t3OitZaXvgFz_lPow/viewform

[attachment https://webrunes.com/img/cards/survey_web3_0.jpg]

This 3-minute survey outlines problems typical for today’s web and possible ways of its further evolution. The survey includes 9 sections, each dedicated to one of the web aspects. Right after you complete the questionnaire you'll be able to compare your views with that of other participants, and take part in the discussion.

Thank you!
```

**Comment by AlexeyAnshakov** [comment]
Please send your ideas how to improve the text.

**Comment by ghost** [comment]
Hi <insert name>,

Looking at your profile and interests I'd like to invite you to learn more about the Future of the Web.

https://docs.google.com/forms/d/e/1FAIpQLSdXFAEP7fZB2QSt0vWbtCxp35e1L-Ue7t3OitZaXvgFz_lPow/viewform

[attachment https://webrunes.com/img/cards/survey_web3_0.jpg]

This 3-minute survey outlines problems that are typical for today’s web and possible ways of its further evolution.  Right after you complete the survey, you'll be able to compare your views other participants, and take part in a discussion.

Thank you!


(are they getting a reward for filling out this survey)

**Comment by AlexeyAnshakov** [comment]
They do, but they can see it on the Card, no need to write about it.

**Comment by ghost** [comment]
I think if you say it in the text it would also be good

**Comment by AlexeyAnshakov** [comment]
Reward is small for western part of world users (most of our contacts) so let's don't pay attention on it. Jillian, when are you going to start?

**Comment by AlexeyAnshakov** [comment]
Please start ASAP. We have little time to reach out all contacts we have. Don't forger to move into "in progress".

**Comment by ghost** [comment]
I have started contacting my LinkedIn contacts on Sunday 

Alwaleed have you started?
I don’t want it to be doubled ...

Please confirm

**Comment by AlWaleed84** [comment]
Not yet,  make sure your LinkedIn shows you’re involved in the space or webRunes while
You do so.  Thanks. 



AlWaleed K. AlShehail

**Comment by AlWaleed84** [comment]
I see it is. Nvm. 


AlWaleed K. AlShehail

**Comment by ghost** [comment]
:) 

I’m worried that LinkedIn I may be banned from sending the message — 

I’ve already lost a few connections -

Alexey what are some of the ways around not spamming or losing important contacts? 

Thanks

**Comment by ghost** [comment]
@alexey any comments?

**Comment by AlexeyAnshakov** [comment]
You have lost contacts you contacted for one purpose - to send them invite. So I believe you shouldn't worry about them.

**Comment by ghost** [comment]
Ok

**Comment by AlexeyAnshakov** [comment]
https://github.com/webRunes/WRIO-InternetOS/issues/1447

**Comment by ghost** [comment]
I am still doing this - is it done for now?

**Comment by AlexeyAnshakov** [comment]
Please continue, but main task is #1447
