### ISSUE TITLE
Missed Airdrop participants

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1432]
We have a lot of users which did something wrong and aren't approved for Airdrop yet https://docs.google.com/spreadsheets/d/1JEy3fIdteHIR_c3FcYKZpmxJYOU-5O62R7WNiduC4hI/edit#gid=1793577065.
Check "Member of https://t.me/webRunesGroup"
many of them are not in the group. Other problems recorded in "Notes".
@jaezed please give to @Hexah07 a direction to contact them (I suppose Telegram is the best way, but you decide) one by one to fix, Message template at https://docs.google.com/document/d/1f1DaL0K-rnYz6-_eWlplV85Sl8JkqLWHYMoB6WOPB14/edit#heading=h.75hjojazu7qt.
Write a list as a comment of those who fixed.
Thank you.

**Comment by ghost** [comment]
I've been banned from Telegram for 3 days for Spam -- I've contacted to the line 111

I think it would be better to just tag everyone who has issues in a comment thread in the bounty- rather than contacting everyone individually

I can make a list

**Comment by AlexeyAnshakov** [comment]
We can't contact them, because they are not in the group.

**Comment by ghost** [comment]
ok - well here is the list i've done up to the first 1000 on the form
Can you add them to the group? and contact them?

https://docs.google.com/spreadsheets/d/1SOLAIV6VpHjZVO1JlcqoGrxlgUgj7u5Kt_JwV2egdRI/edit?usp=sharing

**Comment by AlexeyAnshakov** [comment]
No, I can add to the group who aren't in my contacts.

**Comment by ghost** [comment]
Can we post in the channels that they are supposed to have joined? Saying look at the sheet of your name is white then fix it and give them a timeline to do so or they are kicked out?

**Comment by ghost** [comment]
The ones with issues are about 50% 
That seems pretty high (at least in the first 1000)

**Comment by AlexeyAnshakov** [comment]
We can post for those who joined telegram. But we have to contact who isn't in the group.

**Comment by AlexeyAnshakov** [comment]
Closed.
