### ISSUE TITLE
Telegram partnership

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1433]
@Hexah07 please prepare a list of Airdrop campaigns and sort them by telegram users: 
1k, 2k and so on.

We're going to contact them to propose cross adv. We'll publish and pin for 1 day their Airdrop post, they - ours.

use the search query to find threads
https://www.google.pl/search?dcr=0&ei=eYCZWsqGA4ixsAGDmryIBg&q=site%3Abitcointalk.org+airdrop&oq=site%3Abitcointalk.org+airdrop&gs_l=psy-ab.3...277999.279334.0.279549.7.7.0.0.0.0.120.482.6j1.7.0....0...1.1.64.psy-ab..0.0.0....0.xSZWQJQYb9o

@jaezed please coordinate the task.

**Comment by AlexeyAnshakov** [comment]
@AlWaleed84 I suppose we can use help of @BitEXALT. Please contact him.

**Comment by mopenbtc** [comment]
hi @AlWaleed84 , what can i do for you?

**Comment by AlexeyAnshakov** [comment]
Thanks to @bitexalt we have a start point https://docs.google.com/spreadsheets/d/1sfGJvG0CDtz99GQhCw8TRiSPbqNq7KphrhRkhhFVrb0/edit#gid=400513120

**Comment by AlexeyAnshakov** [comment]
@bitexalt please add more (especially 1-2k). We've agreement with 2 so far (~15 contacted).

**Comment by AlexeyAnshakov** [comment]
@bitexalt please find more 1,5 - 2k groups.
@benjamin421 propose to the groups up to 2k https://docs.google.com/spreadsheets/d/1sfGJvG0CDtz99GQhCw8TRiSPbqNq7KphrhRkhhFVrb0/edit#gid=400513120 partnership OR WGD reward https://github.com/webRunes/WRIO-InternetOS/issues/1384

Message template:
>Hello [name]. We're a team of crypto geeks and developing WRIO Internet OS. It's a platform to create a blockchain-powered decentralized wikipedia of machine-readable and secure data. It can automatically process all incoming content and show it to proper readers based on their interest.
Links: https://bitcointalk.org/index.php?topic=2897802
We'd like to propose you to exchange ads. We offer you to post and pin your ad on https://t.me/webRunesGroup in exchange do the same for our message https://t.me/webRunes/45 for 1 day (or more). Please let us know. Cheers!

**Comment by consciousrepo** [comment]
Will do

**Comment by AlexeyAnshakov** [comment]
Thanks to @bitexalt we have more https://docs.google.com/spreadsheets/d/1sfGJvG0CDtz99GQhCw8TRiSPbqNq7KphrhRkhhFVrb0/edit#gid=400513120. @benjamin421 please push forward.

**Comment by consciousrepo** [comment]
I just sent quite a few messages and got notified by the spam bot I will be blocked until March 24th on my current account, In the meantime I'll push forward with twitter dms, and linkedin, or I can start reaching out on the email list if you'd like. I could also make a new telegram account and reach out from there.

> "Dear Benjamin,
> I’m afraid some Telegram users found your messages annoying and forwarded them to our team of moderators for inspection. The moderators have confirmed the report and your account is now limited until 24 Mar 2018, 15:02 UTC.
> 
> While the account is limited, you will not be able to do certain things on Telegram, like writing to strangers who haven’t contacted you first or adding them to groups and channels.
> 
> Your account will be automatically released on 24 Mar 2018, 15:02 UTC. Please note, that if you keep doing what got you limited and users report you again, the limitations will last longer next time."

**Comment by AlexeyAnshakov** [comment]
Ok, let's proceed with SM at the moment. If you can create a temp telegram, ok, please do.
Nevetheless not sure why this happens. I sent to a ~20 group owners and found a several partners. How many you've reached out already?

**Comment by consciousrepo** [comment]
![Image](https://i.imgur.com/f5qwOTx.jpg) 
It says I was forwarded by other users so it must just be I was reported and if no one reports you, you can continue indefinitely and being blocked isn't an automatic process. When I'm unblocked I will alter the template and try to seem less like a solicitation. And probably ~20 so far today, I marked all I reached as contacted in the above spreadsheet so you can track progress

**Comment by AlexeyAnshakov** [comment]
I see. Jillian, please think with Ben what message can help you to minimize this in the future. Perhaps something very brief as a question.

**Comment by consciousrepo** [comment]
Just made another Telegram so I can continue reaching out today. I'll stay logged in on my old on my phone so I can see responses and use the new on my desktop. I'll also post a new template in this channel shortly

**Comment by AlexeyAnshakov** [comment]
Just as an example: 
>Hi {name}, as an owner of blockchain-oriented telegram channel are you open for partnership?

**Comment by consciousrepo** [comment]
That's perfect, no need to overwhelm them with information right off the bat, I'll run with that and add a single link back to our post or bitcoin talk thread

**Comment by consciousrepo** [comment]
@AlexeyAnshakov I have reached out to every telegram up to ~2k and will let you know if I need approval for a WGD reward for any as replies come in, trying to refrain from offering that initially, would you like me to proceed to higher following groups or focus on SM, LinkedIn, removing duplicates for the email list?

**Comment by AlexeyAnshakov** [comment]
>to proceed to higher following groups or focus on SM, LinkedIn

ok. 
To avoid ban go further with Telegram next day.

**Comment by consciousrepo** [comment]
Will do, I'll shift to the others for today then, thanks

**Comment by consciousrepo** [comment]
I'm suspended on my new Telegram as well and unblocked on my original at the end of today so I will resume this and #1456  , #1384 tomorrow.

**Comment by AlexeyAnshakov** [comment]
Please check https://icodrops.com/ and contact ICOs owners. Especially with a coming, because they have equal telegram user numbers.

**Comment by consciousrepo** [comment]
With the goal of contact still being channel cross promotions?

**Comment by AlexeyAnshakov** [comment]
Correct.

**Comment by AlexeyAnshakov** [comment]
@benjamin421 we have enough users now to cross-ad with others. Please proceed.
