### ISSUE TITLE
ICO participants email list

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1436]
@bitexalt please prepare the list of other ICOs participants like we did for Telegram. We need as much as possible, at least 10,000.

https://docs.google.com/spreadsheets/d/110vWlwzAslB-F4cNTYCRlEO3d-NqcrUPZWBdoPdKphs/edit#gid=0

**Comment by mopenbtc** [comment]
well, i will do that :) @AlexeyAnshakov

**Comment by ghost** [comment]
Can you share the list in google docs and here please

**Comment by mopenbtc** [comment]
slowly begin to accumulate, and more and more. we do this always

https://docs.google.com/spreadsheets/d/1znTpusjHBHCECcPJOz5qppk6g9J8lOj0IFhKI8nvClQ/edit?usp=sharing

**Comment by AlexeyAnshakov** [comment]
It's a list of ICO channels, but not emails. Are you going to add its in Sheet2?

**Comment by mopenbtc** [comment]
not yet up to sheet 2, still continues on sheet 1

**Comment by AlexeyAnshakov** [comment]
@bitexalt progress?

**Comment by mopenbtc** [comment]
this is a new list and contacts

https://docs.google.com/spreadsheets/d/1b9n0fUG4_HCFNPTwNEKneO_z7oUHpIWQrpY-fAbcaUU/edit?usp=sharing

**Comment by ghost** [comment]
Hi @bitexalt let me know if this needs help - Can you add it to in progress please alexey -  or let me know how to change it.

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by mopenbtc** [comment]
email list ? check it
https://docs.google.com/spreadsheets/d/110vWlwzAslB-F4cNTYCRlEO3d-NqcrUPZWBdoPdKphs/edit?usp=sharing

**Comment by AlexeyAnshakov** [comment]
We need much-much more. At least 10,000 but more is better.

**Comment by mopenbtc** [comment]
okay, working on that

**Comment by AlexeyAnshakov** [comment]
Done
