### ISSUE TITLE
Facebook Airdrop/ICO pages

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1439]
@bitexalt Please find and create a list of pages like this one https://www.facebook.com/AlertAirdrop/ . @jaezed we'll contact them later to ask publish info about our Airdrop and coming ICO.

**Comment by ghost** [comment]
https://docs.google.com/spreadsheets/d/1sMpfgJ20af-b6dvqITQrfJtBZ8DxcRKMLx_mYTB30Co/edit?usp=sharing
ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
@jaezed please start to contact them using our webRunes official account. With request to repost our pinned message for 2,500 WGD.

**Comment by ghost** [comment]
Can you add this task to the hub you created and assign me please
ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
It's there https://github.com/webRunes/WRIO-InternetOS/projects/1, just move into "in progress". You're already assigned.

**Comment by ghost** [comment]
Thanks
ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by ghost** [comment]
Hi Alexey 
I am unable to message people from our page - I can only message as myself.
Please advise how you'd like me to proceed.

_"Yes, but only to Facebook users that have messaged your Page first. These messages appear in your Inbox. You will not be able to send a message to a user that hasn't messaged your Page first, even if they have liked your Page."_

**Comment by ghost** [comment]
I also do not know how to move this to in progress

**Comment by AlexeyAnshakov** [comment]
That's ok to contact them via your own account or by using other contacts (email, twitter, so on). We just need to find partners like we do for Telegram. @benjamin421 will help you with it.

**Comment by ghost** [comment]
​Ok - ​
ᐧ

j.

**Comment by ghost** [comment]
I've contacted the first 13 - now I am blocked from sending messages 
Will pick up tomorrow

**Comment by consciousrepo** [comment]
Can you share the file with the list of pages and I will contact as many as I can today without being blocked as well

**Comment by ghost** [comment]
It’s above in this message thread - 

Google sheets

**Comment by ghost** [comment]
https://docs.google.com/spreadsheets/d/1sMpfgJ20af-b6dvqITQrfJtBZ8DxcRKMLx_mYTB30Co/edit?usp=sharing

**Comment by consciousrepo** [comment]
Great! Also a good way to not get blocked in the future is switching up the message just a bit after sending the same one a few times because that's what causes the outlet to recognize you as spam and if it's not the same message even minorly, then you don't get flagged for spam unless a user reports ypu manually but even then it wouldn't block you immediately, a user reporting you just sends a warning to your account in most cases

**Comment by ghost** [comment]
K cool I’ll do that -
I had 3 message templates going on but maybe it was because it was the same link?

**Comment by consciousrepo** [comment]
That could be it, I've learned through trial and error myself, probably is because of the link if you're swapping 3 templates, but even then it shouldn't block you entirely. might depend on the service as well, or some have updated policies I don't know about yet

**Comment by consciousrepo** [comment]
Also do we have any ongoing strategies for our social channels? Fb page, twitter, etc, I see there hasn't been a post on FB in a little over a month, social media management is one of my strong points, If you'd like to make me and admin on the page I'm happy to post content and even run add campaigns with my own funds to grow our exposure

**Comment by ghost** [comment]
Facebook posts daily — the pinned message is the one you’re seeing at the top 

There’s no strategy - I just gather some info and schedule the posts

**Comment by ghost** [comment]
Re all the admin stuff you can ask alexey

**Comment by ghost** [comment]
And Waleed

**Comment by consciousrepo** [comment]
Ah, I see, I'm sorry, I didn't move down, if we're posting daily then that's great! How do you usually see the following grow on a week to week basis? Strategizing content is almost less important than strategizing target views, FB has campaign features that allow you to target very spacific groups based on individual intereats still in large quantity but as long as our following is growing consistently then whatever you're doing is great(:

**Comment by ghost** [comment]
It’s a lot of the airdrop people right now - and bounty people - I think it may be a little squewed from that and not very representative of investors or the people we want to attract

**Comment by consciousrepo** [comment]
I see, I'll share the page simultaneously to some of my friends along with the landing page when its done this week for a start but as we close in on crowdsale it'll be increasingly important we focus on those parties rather than the current exposure reward campaigns

**Comment by ghost** [comment]
Agreed - 

Once everything is ready for investors clean and polished then we can go hard

**Comment by consciousrepo** [comment]
Great, I also replied regarding the landing page in slack, take a look if you'd like,any feedback/criticisms are always greatly appreciated so I can output the best result

**Comment by AlexeyAnshakov** [comment]
@benjamin421 please take care about it.

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by consciousrepo** [comment]
Haven't prioritized above others because issue was "in hold" I will resume then

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by consciousrepo** [comment]
Negotiating with admins of ICX investment group, they dont want adds in channel waiting on approval into crypto currency offerings, and ICO investors pool, which is the best channel I've found so far
