### ISSUE TITLE
Airdropalert & icodrops

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1445]
Please contact them https://airdropalert.com/ and find out how we can join theirs list.

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by AlWaleed84** [comment]
Done. 

AlWaleed K. AlShehail

**Comment by AlexeyAnshakov** [comment]
Please contact them as well https://icodrops.com/

**Comment by AlexeyAnshakov** [comment]
Any progress? Waleed, please coordinate @benjamin421  to help you with it.

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by RoySasson** [comment]
hopefully we will see it tomorrow
