### ISSUE TITLE
Linkedin Groups

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1447]
Please create a message template (like we did for telegram channels/groups) and start to contact Linkedin groups with questions: can we send our survey post.

**Comment by ghost** [comment]
Contact the admins you mean?

Are we just now targeting everyone on LinkedIn? In the blockchain groups?

**Comment by AlexeyAnshakov** [comment]
Correct, admins. We're targeting all crypto users.

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by AlexeyAnshakov** [comment]
Jillian, please push the task with @benjamin421 help.

**Comment by consciousrepo** [comment]
I think LinkedIn is a great outlet for the more professional target user you'd mentioned shooting for, Thanks for the assignment, and @jaezed let me know how I can best aid you in how you've already been proceeding as well

**Comment by ghost** [comment]
Hi ben

I’ve been contacting the admins of crypto related groups to see if we could post our survey on their site 

I have since had limited use of messaging on linked in 

I don’t have a list of groups just the ones I’ve found and contacted asked to join

**Comment by AlexeyAnshakov** [comment]
@jaezed please provide the text for a group owners. We need to promote https://docs.google.com/forms/d/e/1FAIpQLSdXFAEP7fZB2QSt0vWbtCxp35e1L-Ue7t3OitZaXvgFz_lPow/viewform in the groups. I suppose we shouldn't offer a WGD reward to them, they won't be interested. They will post only if find the survey interesting.

**Comment by ghost** [comment]
Hi alexey 

What do you mean owners?

**Comment by AlexeyAnshakov** [comment]
Admins

**Comment by consciousrepo** [comment]
I'll begin requesting to join various groups and once in the group I'll either get an admin to post or since LinkedIn groups are open post, I can post myself as long as it doesn't seem like a solicitation.

**Comment by ghost** [comment]
I’ve been requesting to join and send messages to admins 
I don’t post as that has lead me to being banned 

Each message though is not copy paste it is casual back and forth

**Comment by consciousrepo** [comment]
So maybe I can engage with members casually along with encouraging the admins to post. Again, not to seem like a solicitation, more like a guerrilla marketing tactic.

**Comment by AlexeyAnshakov** [comment]
You're free to try any non-spam tactics.

**Comment by ghost** [comment]
Yes it’s less tacky that way too

**Comment by consciousrepo** [comment]
Agreed, I've had more success in the past in similar groups posting as if I'm unaffiliated and just trying to give a tip or start a conversation. I'll go that route for the time being.

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by ghost** [comment]
I have been starting natural conversations - but on Linked in only

Can you move this to in progress please

**Comment by AlexeyAnshakov** [comment]
Done, but you're able to move ussues by yourself.

**Comment by ghost** [comment]
How? I was unable to drag it or there was no side menu option
ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by consciousrepo** [comment]
Have so far joined multiple bitcoin, blockchain, etc groups and am prioritizing building the webrunes page prior to utilizing those connections.

**Comment by AlexeyAnshakov** [comment]
Any progress?

**Comment by ghost** [comment]
I have been joining groups daily

j.

**Comment by AlexeyAnshakov** [comment]
We need to contact admins with the request to post about wr.io

**Comment by consciousrepo** [comment]
Most groups have rules against solicitation in their channels, but have been "guerrilla marketing" in a few acting as a random discussion participant and suggesting our project

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by AlexeyAnshakov** [comment]
No effect. Closed.
