### ISSUE TITLE
Youtubers & bloggers

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1456]
@BitEXALT please find and prepare the list of bloggers (blog and how to contact) and youtubers (channel and how to contact) linked to semantics (machine-redable, JSON-LD, Linked Data) and blockchain. Our PR guys will contact them.

**Comment by mopenbtc** [comment]
well, i'm working on it

**Comment by AlexeyAnshakov** [comment]
@bitexalt progress?

**Comment by ghost** [comment]
Let me know
ᐧ

j.

**Comment by AlexeyAnshakov** [comment]
Use https://github.com/webRunes/WRIO-InternetOS/issues/1278 for additional info.

**Comment by AlexeyAnshakov** [comment]
https://www.youtube.com/results?search_query=ico+reviews to find reviewers.

**Comment by AlexeyAnshakov** [comment]
https://docs.google.com/spreadsheets/d/1eXINC7iRVej8cyIs6EodJIaFx1ns7Xm7npcuXPCTV_M/edit#gid=0
Jillian, Ben, please start to contact them. We're looking for reviwers for WGD, thus first of all we need a confirmation, they're ok to get WGD as a reward and the price.

**Comment by consciousrepo** [comment]
Will do, Just requested edit access to mark those contacted as contacted so Jillian and I don't double reach out to the same reviewers, also, most of these contacts are emails, do you want us to be using our personals as a contact point?

**Comment by AlexeyAnshakov** [comment]
Let's start with telegram/SM contacts.

**Comment by consciousrepo** [comment]
Will do+thanks for the access @bitexalt

**Comment by benjamin421** [comment]
Thanks for the access @bitexalt

**Comment by AlexeyAnshakov** [comment]
Please post a message template for discussion.

**Comment by consciousrepo** [comment]
> Hi, (Name),
I'm a member of a company launching a new browsing platform based on block-chain technology. We have an ICO to accompany the project launching soon and were wondering if you'd be interested in doing a video about us on your channel? Below I've linked our Telegram group and prototype Hub.
https://t.me/webRunes
https://webrunes.com/

**Comment by consciousrepo** [comment]
Let me know your thoughts on the template and i'll begin contacting channels

**Comment by AlexeyAnshakov** [comment]
```Hello [name]. We're a team of crypto geeks and developing WRIO Internet OS. The platform for developing a machine-readable web featuring automatic data processing. Automatic data processing will enable tuning up browsing experience based on the needs and interests of each separate user. This will pave the way for a user-centric Web 3.0 with its predictive services and search engines of new generation.```

Please add info about whitelisted investors and so on, we have in prev messages.
Link to wrioos.com is enough, no need to provide https://t.me/webRunes

**Comment by consciousrepo** [comment]
https://docs.google.com/document/d/1ZEGQiR3OQk3PrhRP8YN9em36CJEvZ2bT6ZSnWpfoqZg/edit?usp=sharing

I had one youtuber answer me asking me to answer these 7 questions in a document before they committed to a video so here's the doc if needed for anyone else

**Comment by AlexeyAnshakov** [comment]
@AlWaleed84 please help Ben with it. You have TokenMarket's answers.

**Comment by consciousrepo** [comment]
I pulled most of the answers on there now from the token market script document

**Comment by consciousrepo** [comment]
@PeaceloveandCrypto
@abazdj
@CryptoKyle666
@Jeffignacio
Users moving forward with video creation still maintaining line of contact with others but these 4 were enthusiastic and only 1 is directly requesting a reward, waiting to hear back their offer

**Comment by consciousrepo** [comment]
I've updated all contacted and marked all emails that came back as undelivered for invalid address in spreadsheet

**Comment by AlexeyAnshakov** [comment]
> these 4 were enthusiastic 

No details?

**Comment by consciousrepo** [comment]
None new, they are supposedly in the process of making the video for us which will take time, I instructed each to share when done, those 4 were reached on telegram, I will send a follow-up message with each at the end of the week if they don't provide me a progress report

**Comment by consciousrepo** [comment]
Altcoinbuzz note to self

**Comment by AlexeyAnshakov** [comment]
Search for youtubers interested in semantics and web3.
