### ISSUE TITLE
BT threads support

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1458]
https://bitcointalk.org/index.php?topic=3013546
https://bitcointalk.org/index.php?topic=3050884
https://bitcointalk.org/index.php?topic=3109974
https://bitcointalk.org/index.php?topic=3082815
https://bitcointalk.org/index.php?topic=3105937

**Comment by AlexeyAnshakov** [comment]
@jaezed @AcCryptoGhost please help Ben to push our threads. Use prev comments to give your own answers. It's ok to post a few comments only during the day to bump up the threads. Thank you.

**Comment by AcCryptoGhost** [comment]
Cool, got it.

**Comment by consciousrepo** [comment]
Thanks, been a busy few days for me to hop on, I'll be back on a regular schedule tomorrow and can resume commenting at my normal rate
