### ISSUE TITLE
ICO pools

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1459]
Waleed, please check with Eric and Ben ICO pools
https://duckduckgo.com/?q=ico+pool&atb=v102-7__&ia=web
I believe we have to dig this topic and contact some of them to get investors. Share your ideas and opinions.

**Comment by consciousrepo** [comment]
Do we have a spreadsheet of potential contacts yet, and let me know how to best to aid in this task, contacting, finding more potential investors, etc

**Comment by AlWaleed84** [comment]
I’ll let you know soon. 



AlWaleed K. AlShehail

**Comment by consciousrepo** [comment]
http://moonsyndicate.org/
https://discord.gg/97bGsVD
https://t.me/joinchat/HdDtyQ5M8XY6PqeTnUFhag
https://t.me/joinchat/GSRgAUlHdu-rjsuqyyTsTg
https://discordapp.com/invite/UBrmm7h
https://discordapp.com/invite/A8Mj8jg
https://icopoolsgains.com/
https://www.facebook.com/groups/344896579323582
https://t.me/blockchainIG
https://t.me/C1Finance
https://t.me/FiatDaveCryptoPools
http://www.1035club.com/
https://t.me/joinchat/AAAAAE-vb9fdWs1DRnT9Aw
https://discord.gg/RWPt2v8
https://www.facebook.com/groups/306021039924374/
https://t.me/TheICOLabAnnouncements
https://www.crypto-compass.io/
https://t.me/joinchat/Crr1mVM_aemcVCC9tBNdEw
https://primablock.com/
https://t.me/rbigco
https://cryptopros.group/
https://t.me/icobuyclub
https://discord.gg/jckdmTq
https://t.me/joinchat/Crr1mVM_aemcVCC9tBNdEw
https://t.me/ApolloPool
https://t.me/secureicopools
So it looks like ICO pools are commonly used for pre-sales or more exclusive ways to launch an ICO offer, I think we should keep the crowdsale public but joining one or a few of these pools for some big ticket investors may e a good idea. Here's a start, I'll post a draft contact script soon

**Comment by consciousrepo** [comment]
https://messenger.exchange/ I'm connected with the CEO of this exchange on LinkedIn, take a look and let me know thoughts, I can open a line of dialog to list WGD for a pre-listing

**Comment by AlexeyAnshakov** [comment]
I don't think he can be a useful partner. His telegram
https://t.me/telegraf_money
@AlWaleed84 your ideas?

**Comment by consciousrepo** [comment]
Let me know, I'll keep looking as well.

**Comment by AlexeyAnshakov** [comment]
Progress? Use https://wr.io/ in your messages.

**Comment by AlexeyAnshakov** [comment]
What progress?
