### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1495]
Please send your ideas what must be improved https://wr.io/.
And what FAQ do we need: a few from the full list https://github.com/webRunes/WRIO-InternetOS/issues/1464

**Comment by consciousrepo** [comment]
Looking really great, I think the 6 slides was perfect to trim down to while maintaining the story-slide format without having to click through too much content. Only improvement I'd suggest is the faq which we're on and will pick the best few in #1464

**Comment by consciousrepo** [comment]
I think questions 2, 4, and 6 would be the best 3 to have on the page

**Comment by AlexeyAnshakov** [comment]
https://presentation.wr.io/ need to complete it asap.
