### ISSUE TITLE
The WhitePaper improvement. Hours in total: 20.6

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1497]
Please proofread and improve. Add FAQ https://github.com/webRunes/WRIO-InternetOS/issues/1464

**Comment by AcCryptoGhost** [comment]
On it.

**Comment by AcCryptoGhost** [comment]
Although I think I mentioned this before, but Nidish would be better suited to the FAQ.

**Comment by AlexeyAnshakov** [comment]
Please check others ICOs for faq example, most of them aren't tech. BTW, Nidish isn't in contact.

**Comment by AcCryptoGhost** [comment]
Sure, I'll give it a go. And I haven't heard from Nidish in several days, he's kind of dropped off the map. So I'm not sure he'll be joining us after all, but I hope so.

Okay, so this week I'm going to work on:
1. The white paper
2. This: https://docs.google.com/document/d/1XaARfqxqJCv1SCV7A0Ju8FL-15lbWWo7Z3bfMQwiSuo/edit#heading=h.uzrlbc8gzjf
3. The ICO Guide
4. FAQ

What I've already done:
1. I sent you a few hours of work from when I edited the blog posts you sent me (four of them or so) and cleaned up those
2. I edited the landing page and six additional pages and I sent you all the word docs. You told me to move them to 2., but I'm not sure how to move multiple Word docs to this Google doc, so maybe I should just re-edit all of the content in 2.?

**Comment by AlexeyAnshakov** [comment]
Seems it's a problem to convert from word to doc. Please do it manually.

**Comment by AcCryptoGhost** [comment]
You bet, I'll do it.

**Comment by AcCryptoGhost** [comment]
But maybe someone in charge of those blog posts could update the blog by copy/pasting my changes. Here they are:

[Airdrop Campaign.docx](https://github.com/webRunes/WRIO-InternetOS/files/1866376/Airdrop.Campaign.docx)
[Book Announcement.docx](https://github.com/webRunes/WRIO-InternetOS/files/1866377/Book.Announcement.docx)
[What is WRIO ICO.docx](https://github.com/webRunes/WRIO-InternetOS/files/1866378/What.is.WRIO.ICO.docx)

**Comment by AlexeyAnshakov** [comment]
Please use original sources on google docs, it's hard to work with Word.

**Comment by AcCryptoGhost** [comment]
Shoot, I didn't know these sources were in Google Docs. Is it in the 2. link?

**Comment by AlexeyAnshakov** [comment]
https://docs.google.com/document/d/1xkpypzrJRUvX87EpPE7S7CfVcfR-IwXziqgG6b2OAv8/edit
Airdrop - not sure what changed, let's skip if minor changes.
What is WRIO OS https://bitcointalk.org/index.php?topic=3013546.0 ann thread updated to wr.io info

**Comment by AcCryptoGhost** [comment]
Cool. Can you just send me the link to the "What is WRIO OS" Google doc? I'll implement the changes.

**Comment by AlexeyAnshakov** [comment]
No need, it is no longer used:
>What is WRIO OS https://bitcointalk.org/index.php?topic=3013546.0 ann thread updated to wr.io info

**Comment by AcCryptoGhost** [comment]
Ah, I got you.

**Comment by AlexeyAnshakov** [comment]
@AcCryptoGhost please send hours in total for last week.

**Comment by AcCryptoGhost** [comment]
Hey Alexey, I logged 4.65 hours last week.

**Comment by AcCryptoGhost** [comment]
I've gone over all but the last 3 pages of the White Paper.

**Comment by AlexeyAnshakov** [comment]
@AcCryptoGhost please send time for this week and set a remider to repeat at the end of each week. Thanks.

**Comment by AcCryptoGhost** [comment]
For sure, I'll remember to do that. This past week I worked 10.67 hours.

**Comment by AlexeyAnshakov** [comment]
Added

**Comment by AlexeyAnshakov** [comment]
Hours?

**Comment by AcCryptoGhost** [comment]
I was going to let you know later this evening: total hours this week = 3.5.

**Comment by AlexeyAnshakov** [comment]
Updated

**Comment by AcCryptoGhost** [comment]
Only .5 hours this week.

**Comment by AcCryptoGhost** [comment]
.8 hours this past week.

**Comment by AcCryptoGhost** [comment]
.5 hours last week (just including today's work as last week's).
