### ISSUE TITLE
Affiliate and referral program

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1505]
Roy's quote:
```
I have started presenting to waleed and Eric my plan regarding an affiliate and referral program . It's a great way for generating diversified yet targeted traffic for the Ico . The main idea is that a user publish a link yo the Ico with his unique tracker id , and if someone lands in the Ico site from this link and make an investment , the user the referred this investor gets rewarded with 5-10% of the tokens.

I have made some research in other ICOs and found some very easy to set up referrals programs , they will help the user publish a post in SM with just a click .

I would be able to lead this forward since I've been doing affiliate marketing in the past.

The programs are easy to integrate and they will help with the process , costs between 29$-300$ a month. The marketing part is easy to write an very straight forward
Will send you my favorite 2 :
https://m.youtube.com/watch?t=25s&v=NV6vn8G_wtE
https://www.leaddyno.com/product-tour/overview/
I like to think of marketing as 50% psychology - and when it comes to investing in ICO the uncertainty people have is huge . If someone will come from a link that has referred him like a site that reviews ico or a friend that recommended , it will reduce fear factor by some.

Since the affiliate program must be connected to payments , we could add it only after we sort the Ico provider issue . 
After we have it set , we can choose an affiliate system and integrate it. 
Then we could start promote it (edited)
```

Please share your ideas and comments.

**Comment by ericegnet** [comment]
I actually support and stand by this approach. It different cast a wider net of expposure for us. I checked out https://www.leaddyno.com and it seems like a good option. He said he had a second recommendation as well.

**Comment by AlWaleed84** [comment]
As long as the service we use doesn’t hurt the WRIO brand or cheapen it, then we go ahead with the approach. 



AlWaleed K. AlShehail

**Comment by consciousrepo** [comment]
I agree, the approach has no net negative other than if it's not done the right way so I'm all for rolling our a system if it maintains brand consistency

**Comment by AlexeyAnshakov** [comment]
Ok, after @RoySasson joins us we learn more about his strategy and ideas.

**Comment by RoySasson** [comment]
The marketing communications should be aligned in all channels. I can't find how it can do harm to our company . This will actually open many doors for us with partners that feels they can provide us the right traffic - they will have a tool (their unique link) to promote us without us needing to tailor make each partner a new contract .

**Comment by RoySasson** [comment]
It is much more simple for a user to understand and apply than airdrop and bounty where they need to put alot of work in different SM , twitting posting and etc. 
Here they only need yo share a link and get percentage of their referred traffic investments

**Comment by RoySasson** [comment]
@ericegnet , my second preferred affiliate program is Affise.com , which is more advanced but costs more as well ( starts from 300$\month) . I don't think we need it for our purpose
