### ISSUE TITLE
Affliates campaign

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1543]
@RoySasson please prepare a full cycle user story:  from finding (ref link) our campaign to proceed through it and finaly sending own ref link (cycle looped). Step-by-step, so we can see what we can to improve

**Comment by AlexeyAnshakov** [comment]
Improve the text of 
![image](https://user-images.githubusercontent.com/604410/39117380-194c34b2-46e7-11e8-9d4b-f134e1401322.png)

**Comment by ghost** [comment]
Hi - I am doing a text for this? - For what channel? Context?

Thanks

j.

**Comment by AlexeyAnshakov** [comment]
I added others to help @RoySasson to prepare the affilates campaign.

**Comment by RoySasson** [comment]
There are 2 ways for us to work on the airdrop campaign : 
1. Publishing airdrop ads in SM , using our own trackers implemented in these ads , to see which ones are working the best for us ( i will create several link for the different sm channels and ads)  .
From there the user will be redirected to wr.io/airdrop.html?afmc="our-preset-tracker" , and after completing all tasks to qualify , we will get new LEAD in our backend , check it and reward it later on . 

2. Through affiliate campaign :

a. the affiliate advertise our airdrop campaign with his own unique ref link .
2. A user that clicks the affiliate's promotion will be redirected to wr.io/airdrop.html?afmc="affiliates-id" (the affiliate will see VISIT in his dashboard at that point) . If the user continues and completes all tasks , affiliate will get a LEAD in his dashboard . After checking the lead by us , the user and affiliate will be credited and rewarded later on . 

So We need 2 campaigns texts : 
1. for affiliate campaign 
2. for direct airdrop campaign 

As for the attached ad :
I would make the 25WGD text the bigger one and 7500000 smaller one .
In the bottom small fonts , I would start with the simple and important info : Get rewarded 250 wgd for each submitted referral and 5% of referred user deposits

**Comment by AlexeyAnshakov** [comment]
We need a more detailed story, like
1. User see a SM ref link (we need to prepare a good text, so users can share in one click). Ref link says he will get additional 50 tokens (or +25% of airdrop, what works better @CryptoJH. +$2 sounds not too good for me)
2. Clik and open page with additional info about additional reward (text must be prepared)
..
and so on.

**Comment by AlexeyAnshakov** [comment]
Progress?

**Comment by consciousrepo** [comment]
Did you want the user experience written in text for review? If not I'd say we completed this task yesterday, Jun is beginning promotion tomorrow for the weekend rush

**Comment by AlexeyAnshakov** [comment]
@AlWaleed84 please check with @RoySasson and @benjamin421 step by step the user's way to be sure, we're ready.
