### ISSUE TITLE
Backup. Reward 14 USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#166]
Create auto back for AWS ec2. Must be stored several copies:
a first one - every 24h, name 1d
second: every 3 days, name 3d
third: every 7 days, name 7d
forth: every 30 days, name 30d

Every copy must be rewrited by a new version to avoid redundancy.

**Comment by umairadeeb** [comment]
I don't understand. What type of backup do you want on this repo? What files do we need to backup and where to?

**Comment by AlexeyAnshakov** [comment]
We must backup EC2 valumes to snapshots.

**Comment by umairadeeb** [comment]
Automated snapshots of both volumes of our instance has been set up. Backups will triggered on every 10th, 13th, 17th, and 1st day of month starting from today, and will be removed after 30 days.

Logs of the backup operation are stored in /var/log/ec2-automate-backup.log file.

Let me know if this if sufficient or do we need anything else.

**Comment by AlexeyAnshakov** [comment]
We have a lot of copies please check

**Comment by umairadeeb** [comment]
There was an issue in the cron job that I have fixed now. Let's monitor this on 10th of this month.

**Comment by AlexeyAnshakov** [comment]
Please check once again, we have snapshots from December 25, 2014

**Comment by umairadeeb** [comment]
This script will not remove snapshots that it did not create. Do you want me to manually remove those two snapshots from 2014?

**Comment by AlexeyAnshakov** [comment]
Please do

**Comment by AlexeyAnshakov** [comment]
Please do

On Sun, Jul 12, 2015 at 6:57 PM, Umair A. Shahid <notifications@github.com>
wrote:

> This script will not remove snapshots that it did not create. Do you want
> me to manually remove those two snapshots from 2014?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webRunes/WRIO-InternetOS/issues/166#issuecomment-120733787>
> .
>



-- 
Alexey Anshakov,
mobile: +375 29 7-530-531
skype: alexey_anshakov
email: alexey.anshakov@gmail.com <alexey.anshakov@gmail.com>

**Comment by umairadeeb** [comment]
![image](https://cloud.githubusercontent.com/assets/8775209/8639046/5ae8a908-28e7-11e5-87da-dda8daa31948.png)

I think we should not remove these snapshots.

**Comment by AlexeyAnshakov** [comment]
Ok

On Sun, Jul 12, 2015 at 8:43 PM, Umair A. Shahid <notifications@github.com>
wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/8775209/8639046/5ae8a908-28e7-11e5-87da-dda8daa31948.png>
>
> I think we should not remove these snapshots.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webRunes/WRIO-InternetOS/issues/166#issuecomment-120749745>
> .
>



-- 
Alexey Anshakov,
mobile: +375 29 7-530-531
skype: alexey_anshakov
email: alexey.anshakov@gmail.com <alexey.anshakov@gmail.com>
