### ISSUE TITLE
Recharts implementation on Feed. Total hours: 17

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1671]
1. Implement http://recharts.org. Display temperature via SimpleLineChart in the Feed above current text of sensor's data.
2. Chart should display one mesurement at the time for 24h period. Take max and min (Y axis) from max and min sensor's mesurements. X axis = 00 to 23h, step 1h.
3. Add dropbox to choose mesurement. Don't include boolean for now, only with numbers.
4. Add links, only the first should be active for now: "24h  ·  1w  ·  1m  ·  1y  ·  All".
---
**[Estimation: 10h]**

**Comment by AlexeyAnshakov** [comment]
1. add dashed background lines for x and y axises.
2. display Hours scale on X
3. update the chart after selecting an option in the dropdown.
Don't show "Select Feed", show the first mesurement by default.
4. State - boolean
---
**[Estimation: 4h] + 3**

**Comment by AlexeyAnshakov** [comment]
If there no data 
```
"value": ""
```
Display with gaps http://recharts.org/en-US/examples/LineChartConnectNulls

**Comment by AlexeyAnshakov** [comment]
Add
```
The device was disabled
```
On the feed chart for null values.

**Comment by umair-khan-PDW** [comment]
Recharts don't support to add tooltip for null values.
