### ISSUE TITLE
Add SSL

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#17]
https://www.startssl.com/
https://letsencrypt.org/howitworks/technology/ as an option

**Comment by AlexeyAnshakov** [comment]
https://letsencrypt.org/
https://www.eff.org/deeplinks/2014/11/certificate-authority-encrypt-entire-web
https://letsencrypt.org/howitworks/
https://letsencrypt.org/howitworks/technology/
https://github.com/letsencrypt/acme-spec/blob/master/draft-barnes-acme.md
http://www.ietf.org/rfc/rfc2314.txt
http://tools.ietf.org/html/rfc2818
https://www.globalsign.com/ssl-information-center/types-of-ssl-certificate.html
https://cabforum.org/ev-code-signing-certificate-guidelines/
https://en.wikipedia.org/wiki/X.690#DER_encoding
http://tools.ietf.org/html/rfc5246

**Comment by umairadeeb** [comment]
This project "Let's encrypt" looks promising, and the fact that it is sponsored by the Linux Foundation makes it more authentic.
I think we can try this.

**Comment by AlexeyAnshakov** [comment]
https://letsencrypt.org/2015/12/03/entering-public-beta.html please implement.
https://letsencrypt.readthedocs.org/en/latest/

**Comment by AlexeyAnshakov** [comment]
Can be useful comment:

```
webroot.
By default domain ownership is checking by http (80 / 443 ports). You have to copy from dir "examples" file "cli.ini" into /etc/letsencrypt/cli.ini and uncomment
authenticator = webroot webroot-path = /var/www/html/
webroot-path must be pointed to dir document_root. In this case letsencrypt will do domain checking with static files without http server. 
```

**Comment by AlexeyAnshakov** [comment]
Can be used docker dmp1ce/nginx-proxy-letsencrypt

**Comment by AlexeyAnshakov** [comment]
@michbil please fix URLs for proper SSL working.
