### ISSUE TITLE
PEM key

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#173]
Please help with 
http://docs.travis-ci.com/user/deployment/custom/
to deploy on Github via Travis.

**Comment by umairadeeb** [comment]
Automated snapshots of both volumes of our instance has been set up. Backups will triggered on every 10th, 13th, 17th, and 1st day of month starting from today, and will be removed after 30 days.

Logs of the backup operation are stored in /var/log/ec2-automate-backup.log file.

Let me know if this if sufficient or do we need anything else.
