### ISSUE TITLE
Video tutorial from A to Z

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#1879]
Prepare a brief script to show deployment and use. E.x.
1. Registration on the testbed
2. Setting up jFed
3. Deployment on Heroku
etc.

After approval, we'll start developing a video tutorial. You will need to go through and record all the steps, including deployment on wr.io Heroku for the further demo with jFed controlling.
Do not worry about voice recording, we will use subtitles. It will help us to translate to other languages if necessary.

The task shouldn't take more than 4h in total.

**Comment by YAS-CODE** [comment]
requirement:-
-an account on ilabs
-installed jFed and properly working on Linux platform

steps:
- get your certificate from https://authority.ilabt.iminds.be/getcert.php
- install it your system
- reserve a node from URL https://boss.wilab1.ilabt.iminds.be/inventory/?viewMode=inventory#
- note down the node id of the reserved node
- download jfed experimental toolkit from WRIO git
- extract "jfed experimental toolkit" and insert reserved node-id into iot.rspec from it
- to start an experiment goto Jfed Experimental tools and click on "Open Espec"
	- click on "local dir" and browse to extracted "jfed experimental toolkit", Click on Start Espec
	- mention experiment name, select a project and mention duration of experiment and start experiment
	- Wait for experiment to be started successfully

**Comment by AlexeyAnshakov** [comment]
Add demo of deployment on Heroku. About the config file. Show how the testbed reacts on changes on feed and turn on/off sensor.

**Comment by AlexeyAnshakov** [comment]
Add subtitles as a text here in the issue for created tutorials. No need to follow up the voice: subtitles must contain a timestamp and describing text.
