### ISSUE TITLE
iFramely. Reward: 10 USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#19]
Setup on our server https://github.com/itteco/iframely to embedded 3rd parties posts. Setup documentation

> https://iframely.com/docs/host

**Comment by umairadeeb** [comment]
As discussed, I have installed iframely on dev instance using opsworks on port 5006, and also configured reverse proxy on dns-name, iframely.webrunes.com.

Here is the url to test this setup:
curl -X GET http://iframely.webrunes.com/iframely?uri=http://twitter.com
