### ISSUE TITLE
Dev deploy

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#198]
Please set up a proxy reverse for

> dev.wrioos.com

s3 bucket, so we can launch all dev apps at
http://dev.wrioos.com/WRIO-InternetOS/WRIO.js
http://dev.wrioos.com/Core-WRIO-App

**Comment by umairadeeb** [comment]
I have configured dev.wrioos.com bucket, can you please configure Route 53 to point to Amazon name servers.

**Comment by AlexeyAnshakov** [comment]
It's done
