### ISSUE TITLE
MongoDB. Reward 20 USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#200]
Please switch MySQL on AWS OPS Works to MongoDB.
@AM-NiceDay provide a hand to @umairadeeb if need it. Thanks.

**Comment by umairadeeb** [comment]
There is no out of the box Layer support for MongoDB on OpsWorks, I tried using chef custom cookbook and community's existing recipes but it didn't work.

Right now I have installed it manually on instance and its working fine.
