### ISSUE TITLE
UTC time

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#217]
Please update server time to UTC±00:00 
https://en.wikipedia.org/wiki/UTC%C2%B100:00
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html

**Comment by umairadeeb** [comment]
Timezone is already set to UTC. What else do you need?

![image](https://cloud.githubusercontent.com/assets/8775209/8460269/ade4aed0-203c-11e5-86cb-cc61f16f2985.png)

**Comment by AlexeyAnshakov** [comment]
Make sure it's setup as UTC±00:00

**Comment by umairadeeb** [comment]
Yes it is setup as UTC 00:00:00
