### ISSUE TITLE
Установка Gulp

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#22]
Интегрировать в процесс разработки Gulp

Ссылки в помощь:
http://martinwolf.org/2014/06/16/screencast-getting-started-with-gulp-js/
http://habrahabr.ru/company/dnevnik_ru/blog/181352/ хоть и касательно grunt
https://medium.com/@webprolific/getting-gulpy-a2010c13d3d5 Getting gulpy
http://habrahabr.ru/company/trackduck/blog/230257/
http://frontender.info/gulp-browserify-starter-faq/
http://hmphry.com/gulp/

**Comment by AlexeyAnshakov** [comment]
GruntLauncher в галерее VS http://visualstudiogallery.msdn.microsoft.com/dcbc5325-79ef-4b72-960e-0a51ee33a0ff
Для работы с Grunt, Gulp, NPM или Bower. Позволяет легко запускать задачи Grunt/Gulp напрямую из Solution Explorer и обновлять компоненты Bower.

**Comment by spirinvladimir** [comment]
gulp интегрирован в задаче:
https://github.com/webRunes/WRIO-InternetOS/issues/151
Используется плагин:
gulp-download
для скачивания зависимостей перед сборкой bundle-ла.
