### ISSUE TITLE
Minimization and GZIP

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#259]
Add gulp gzip minimization & function fro production versions of js and css files.
http://www.rightbrainnetworks.com/blog/serving-compressed-gzipped-static-files-from-amazon-s3-or-cloudfront/

**Comment by AlexeyAnshakov** [comment]
После перехода на dev и production нам нужно будет оставлять неужатую версию для dev и оптимизированную для production.

**Comment by michbil** [comment]
@AlexeyAnshakov Как альтернативный вариант можно всегда включать углификацию кода в production, и для удобства отладки подключать source maps http://habrahabr.ru/post/178743/ http://stackoverflow.com/questions/28087674/gulp-browserify-6to5-source-maps

**Comment by michbil** [comment]
Can be closed, i think
