### ISSUE TITLE
React-tools now deprecated

### ISSUE THREAD

**Issue by michbil** [webRunes/WRIO-InternetOS#269]
We are using react-tools to build WRIO-InternetOS, react-tools build takes much time, and becomes very annoying when using docker. 
https://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html

Facebook guys suggesting using babel instead of react tools. I think we should move to babel for WRIO-InternetOS, especially because we using babel in webGold application, and it's recommended itself as a good tool.
Good benefit of using babel is that it offers ES6 language features by default too.

My proposal:
https://github.com/webRunes/WRIO-InternetOS/pull/268

**Comment by AlexeyAnshakov** [comment]
Sounds good.
