### ISSUE TITLE
Geth monitoring script

### ISSUE THREAD

**Issue by michbil** [webRunes/WRIO-InternetOS#333]
Make monitoring script for geth process: if geth process down, then restart process. Using monit or supervisord, whatever more suitable.

Geth script location: /home/deploy/geth/geth

**Comment by umairadeeb** [comment]
This is completed.
monit will look for process "geth" and will try to execute /etc/init.d/geth-deploy init script if geth process is not running.

```
Nov 23 12:23:50 webgold-app0 monit[26057]: 'geth' process is not running
Nov 23 12:23:50 webgold-app0 monit[26057]: 'geth' trying to restart
Nov 23 12:23:50 webgold-app0 monit[26057]: 'geth' start: /etc/init.d/geth-deploy
```
