### ISSUE TITLE
Don't use * asterisk in package json

### ISSUE THREAD

**Issue by michbil** [webRunes/WRIO-InternetOS#379]
Now we have many \* versions in our package.jsons

for example:

```
 "body-parser": "*",
    "debug": "*",
    "depd": "*",
```

Small change in any included library can break build any time in future, so I suggest to update all asterisks to most recent working library versions.

**Comment by AlexeyAnshakov** [comment]
Agreed.

**Comment by michbil** [comment]
Issue is actual for other wrio apps as well, i will reference this issue when will be fixing other apps too

**Comment by michbil** [comment]
Issue can be closed now
