### ISSUE TITLE
Help message

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#403]
См. Default-WRIO-Theme/sign_in.htm : при небольших разрешениях отображается

> First time here?
> Pay attention to the icon above

При нажатии на "x" записывать в куки, что пользователь уже видел это сообщение и больше не отображать.

**Comment by AlexeyAnshakov** [comment]
Уведомление не видно.

**Comment by victorpavlenko** [comment]
![image](https://cloud.githubusercontent.com/assets/5157416/11767111/8dab91ee-a1b3-11e5-834f-b364aedfeba8.png)
Не залилось. Тут ничего нет, а должен быть мой Alert компонент

**Comment by AlexeyAnshakov** [comment]
Потому что билд проходит с ошибкой

**Comment by victorpavlenko** [comment]
Можно закрывать

**Comment by AlexeyAnshakov** [comment]
Отображается

> Внимание - эксперементальный проект, в стадии разработки. Заявленные функции будут подключаться по мере его развития.

про который я ничего не говорил, но пусть остается, см. внимательно задачу
![image](https://cloud.githubusercontent.com/assets/604410/11890612/cdfccf8e-a55e-11e5-9430-4d62b955c122.png)
После закрытия больше не должны появляться для данного пользователя (ставить флаг в куки). Проверка должна идти от обратного - всегда скрывать и отображать только если нет флага в куки.

Помимо этого перестало работать меню в IE
![image](https://cloud.githubusercontent.com/assets/604410/11890630/0ff8ac46-a55f-11e5-8743-45b6d18ca8a7.png)

**Comment by victorpavlenko** [comment]
Все сделал, делаю PR. В IE все работает проверил во всех версиях. Может быть в прошлый раз что то не собралось до конца, такое у меня тоже случается иногда, когда не успевает дособраться проект после изменений

**Comment by AlexeyAnshakov** [comment]
> First time here?
> Pay attention to the icon above . Click it to open a side menu

отображается для всех разрешений, должно только для mobile

**Comment by AlexeyAnshakov** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/604410/12017587/ef4dd488-ad58-11e5-934a-92167adc2db0.png)
не отображается правильно, не видно полностью сообщение

**Comment by AlexeyAnshakov** [comment]
Сообщения продолжают появляться после своего закрытия.

**Comment by AlexeyAnshakov** [comment]
привязка идет неверно. например, на странице
http://wrioos.com/
удалил сообщение, но оно видно на
http://webrunes.com/blog.htm

**Comment by AlexeyAnshakov** [comment]
Надо поменять флаг отображения сообщений, чтобы он по умолчанию не отображался и подгружался если его нет в локалстородже, иначе при отключенгии он всегда появляется при загрузке страницы и после исчезает.
