### ISSUE TITLE
Nodejs ports(5000-5005) shoudn't be visible from outside world

### ISSUE THREAD

**Issue by michbil** [webRunes/WRIO-InternetOS#404]
On amazon EC2 instance nodejs apps should not be visible from outside world, so services must be visible only via apache reverse proxy.

I think should be fixed closer to going to production.

**Comment by umairadeeb** [comment]
Access has been disabled on port 5000 and 5001.

**Comment by AlexeyAnshakov** [comment]
@michbil please check

**Comment by AlexeyAnshakov** [comment]
I believe we have to disable all ports.

**Comment by umairadeeb** [comment]
Only 5000 and 5001 were opened. You can try accessing all of them using telnet.
