### ISSUE TITLE
Rename and move. Reward: 7 USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#45]
Rename WRIO-InternetOS/main.js to WRIO-InternetOS/wrio.js

Move article from https://github.com/webRunes/Plus-WRIO-App/tree/master/Widget/article.html to https://github.com/webRunes/Default-WRIO-Theme/Widget/article.htm (please note html->htm, now all templates and json-ld will have .htm). We add version in URL, more info here https://github.com/webRunes/Default-WRIO-Theme/issues/11
The same for Menu:
https://github.com/webRunes/Plus-WRIO-App/tree/master/Widget/menu.html ->
https://github.com/webRunes/Default-WRIO-Theme/Widget/Menu/v1.htm

Rename for Plus too:
https://github.com/webRunes/Plus-WRIO-App/blob/master/Widget/template.html ->
https://github.com/webRunes/Plus-WRIO-App/blob/master/Widget/Plus/v1.htm
and Login:
https://github.com/webRunes/Login-WRIO-App/blob/master/Widget/login.html ->
https://github.com/webRunes/Login-WRIO-App/blob/master/Widget/Login/v1.htm

**Comment by AlexeyAnshakov** [comment]
Article widget have to be dynamic, not static as did https://github.com/webRunes/WRIO-InternetOS/pull/49/files, please just move it from https://github.com/webRunes/Plus-WRIO-App/blob/master/Widget/article.html

**Comment by umairadeeb** [comment]
@AlexeyAnshakov, @wall2003: Let me know if my help is required here

**Comment by AlexeyAnshakov** [comment]
Проверить что нужно изменить в http://wrio.s3-website-us-east-1.amazonaws.com/WRIO-InternetOS/WRIO.js, почему webrunes.com не работает

**Comment by wall2003** [comment]
http://wrio.s3-website-us-east-1.amazonaws.com/Default-WRIO-Theme/widget/article.htm
http://wrio.s3-website-us-east-1.amazonaws.com/Default-WRIO-Theme/widget/menu.htm
http://wrio.s3-website-us-east-1.amazonaws.com/Titter-WRIO-App/widget/titter.htm
http://wrio.s3-website-us-east-1.amazonaws.com/Plus-WRIO-App/widget/plus.htm

отсутствуют эти ресурсы.

2015-01-19 20:56 GMT+03:00 Alexey Anshakov notifications@github.com:

**Comment by AlexeyAnshakov** [comment]
webrunes.com в рабочем состоянии
