### ISSUE TITLE
AWS intance purchase

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#450]
Please send me a proper small On-Demand Instance we can use for dev
http://aws.amazon.com/ec2/pricing/
I will buy it.
Is it

```
t2.micro    1   Variable    1   EBS Only    $0.013 per Hour
```

?

**Comment by umairadeeb** [comment]
this is completed.

**Comment by AlexeyAnshakov** [comment]
Delete unused volumes.

**Comment by umairadeeb** [comment]
One unused volume is deleted. Other volumes belong to dev instance which is stopped right now
