### ISSUE TITLE
Travis invalidate aws CloudFront cache

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#451]
Please add invalidation
http://www.mikitamanko.com/blog/2014/10/26/travis-invalidate-aws-cloudfront-cache/
every time we update s3. It would be great to invalidate only updated files.

**Comment by AlexeyAnshakov** [comment]
@michbil FYI

**Comment by umairadeeb** [comment]
This is completed. Waiting for travis build now..
