### ISSUE TITLE
Github pages SSL setup

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#454]
Please help with Github pages SSL setup. Seems Github has some catches with it.
What I've found
https://konklone.com/post/github-pages-now-supports-https-so-use-it
https://me.net.nz/blog/github-pages-secure-with-cloudflare/
Please let me know what is the best option to open 
http://webrunes.com
as
https://webrunes.com

**Comment by AlexeyAnshakov** [comment]
@michbil FYI

**Comment by umairadeeb** [comment]
This is completed.
