### ISSUE TITLE
Wiki. Reward 10 USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#50]
Please add info for our and 3rd party developers to
https://github.com/webRunes/WRIO-InternetOS/wiki/Create-new-project
how to create a brand new project from step "we have an empty GitHub repo". Most important is how to create conf file and where to upload in server and what have to be done to start nodejs "Hello World" application.

**Comment by AlexeyAnshakov** [comment]
@umairadeeb , please help @bhushano7 with it and add info how to https://github.com/webRunes/WRIO-InternetOS/wiki/Deploy-on-OpsWorks
Add info about keys generation too.

**Comment by AlexeyAnshakov** [comment]
Any progress?

**Comment by umairadeeb** [comment]
Will do this tomorrow.

**Comment by umairadeeb** [comment]
This is done. Please review it.

**Comment by AlexeyAnshakov** [comment]
@umairadeeb , thanks. Will close asap @bhushano7 write his part

**Comment by bhushano7** [comment]
@AlexeyAnshakov , can you explain me, what should I need to do exactly ?

**Comment by AlexeyAnshakov** [comment]
Any update?

**Comment by bhushano7** [comment]
I will update after completion of Titter project.
