### ISSUE TITLE
Menu widget. Reward ??? USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#51]
Сделать menu widget в правой части http://webrunes.github.io/webRunes-WRIO-Hub/1WJyH1k7_en-US.html
Главная задача - автогенерация через main.js меню в правой части страницы на основе json-ld.

Каждая страница состоит из двух или более json-ld частей (см. Default-WRIO-Theme/2ziwMaIk_en-US.htm):
первая - часть для wrio парсера, техническая информация по правилам как обработать страницу, пока пропустить.

вторая, сама статья: пост, о пользователе (биография и пр. данные), о компании (история создания и пр.) и т.д. в соответствии с http://schema.org/Article
Разделы для них будут на основе темплейтов WRIO, разработаны они будут позже, пока это не важно и я сам ручками прописываю их, сейчас надо лишь считывать и отображать справа меню аналогично тому, как это выглядит на странице Default-WRIO-Theme//2ziwMaIk_en-US.html

третья, расширенная - есть не у всех, это дополнительная часть характерная для профайлов пользователей, компаний и пр. перечисленных здесь объектов: http://schema.org/Thing -> см. More specific Types
в примере Default-WRIO-Theme//2ziwMaIk_en-US.html рассмотрен пример для профайла.
Для простых постов и статей этой части не будет, для остальных же данные из нее будут вкрапляться в статью.
Пока ее игнорировать, еще в разработке.

P.S.
- Хотя в примере Default-WRIO-Theme/2ziwMaIk_en-US.htm есть фотография пока ее вставлять не нужно.
- ссылка "Contacts" отобразить пока просто ссылкой в тикете, сделаем позже.
- keywords пока игнорировать.
- цифры в начале абзацов от 1 до 6 лишь для простоты отслеживания соответствия текста в прототипе и json-ld файле.

**Comment by wall2003** [comment]
Главная задача - автогенерация через main.js меню в правой части страницы
на основе json-ld.
это не понятно, mainjs до сих пор никакой генерацией не занимался, на
странице есть виджеты, которые имею каждый свою функциональность и
соответственно ей и работают...

у тебя на странице все три json-ld одинаковые, не знаю, как виджет меню
найдет свой? ты предлогаешь, загрузить ему все три, а потом искать нужный
по чем? не проще ли было отличать их по айди например и сразу находить тот
что нужен, это теперь уже относится и ко всем остальным виджетам которые
работают с этой страницей...

тестовую страницу /2ziwMaIk_en-US.html нужно разместить на
webrunes.github.io, что бы был доступ к ней

и на сколько я понял, сейчас процесс разработки и тестирования становится
крайне проблематично...

Павел

2014-12-13 8:33 GMT+03:00 Alexey Anshakov notifications@github.com:

**Comment by AlexeyAnshakov** [comment]
> это не понятно, mainjs до сих пор никакой генерацией не занимался, на
> странице есть виджеты, которые имею каждый свою функциональность и
> соответственно ей и работают...

До этого все виджеты разрабатывались под функционал приложений. Menu - это дополнительная часть обработки для всех сущностей: статей, профайлов и пр. Это для второго json-ld, для самих данных, а не функционала приложений поверх вроде Login, webGold и пр.

> все три json-ld одинаковые

что значит одинаковые? У всех из них свой набор данных, свой набор ключ-значений. Разбивка json-ld всегда одна и все идут по порядку, т.е. для построения страницы всегда используется второй.

> ты предлогаешь, загрузить ему все три

они всегда будут грузиться все вместе, это же просто html с json-ld вставками. Вся разница от предыдущей версии в том, что раньше был один json-ld, а теперь он разбит на части.

> не проще ли было отличать их по айди например

Если порядка следования кусков json-ld недостаточен, то можно добавить ID к ним. Напоминаю, что не зависимо от этого все равно грузятся все json-ld, они все должны быть обработаны main.js (виджеты приложений мало будут взаимодействовать с json-ld, в основном они будут получать данные от родительских приложений): первый json-ld для информации какой темплейт использовать (как писал, пока игнорировать), вторая часть - информация для отображения данных самой страницы, третья часть - доп.данные профайлов и др. сущностей на базе которых можно будет строить хабы (на данном этапе тоже пока игнорировать)

> и на сколько я понял, сейчас процесс разработки и тестирования становится
> крайне проблематично...

почему? И разработка и тестирование как раз-таки очень просты: каждый разработчик отвечает за свою часть разработки, после идет автобилд с прогоном автотестов.

**Comment by AlexeyAnshakov** [comment]
https://github.com/webRunes/WRIO-InternetOS/issues/46
