### ISSUE TITLE
iframely hub

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#515]
Please create app and hub links for 
https://iframely.wrioos.com/
ask @umairadeeb about iframely on server-side, it's already there. 
At this moment we must see hub and one command
https://iframely.wrioos.com/embed/
so it would looks like:
https://iframely.com/embed/

**Comment by AlexeyAnshakov** [comment]
It works before here
http://iframely.wrioos.com/iframely?uri=https://500px.com/photo/98284235/d-e-t-e-r-m-i-n-a-t-i-o-n-by-david-ruiz-luna
but not now, @umairadeeb please fix

**Comment by umairadeeb** [comment]
This is completed.

**Comment by AlexeyAnshakov** [comment]
@balthazzar please create hub. Then we can proceed with
https://iframely.wrioos.com/iframely?uri=https://secure.flickr.com/photos/umairadeeb/22776127720/ working example.
