### ISSUE TITLE
New hubs

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#548]
Please set up https://opencopyright.wrioos.com
https://github.com/webRunes/opencopyright.wrioos.com-WRIO-Hub

https://tutorial.wrioos.com
https://github.com/webRunes/tutorial.wrioos.com-WRIO-Hub

**Comment by umairadeeb** [comment]
this is completed.

**Comment by AlexeyAnshakov** [comment]
Please add new hubs for webrunes.org not webrunes.com:
alternative.webrunes.org = https://github.com/webRunes/alternative.webrunes.org-WRIO-Hub
esperanto.webrunes.org = https://github.com/webRunes/esperanto.webrunes.org-WRIO-Hub
education.webrunes.org = https://github.com/webRunes/education.webrunes.org-WRIO-Hub
help.webrunes.org = https://github.com/webRunes/help.webrunes.org-WRIO-Hub

**Comment by umairadeeb** [comment]
This is completed. Please verify.

**Comment by AlexeyAnshakov** [comment]
Please add aa.wr.io = github.com/AlexeyAnshakov/aa.wr.io-WRIO-Hub

**Comment by umairadeeb** [comment]
This is done.
