### ISSUE TITLE
React and flux. Reward 190 USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#55]
Open in Chrome http://webrunes.com/. You will see generated page on the fly via wrio.s3-website-us-east-1.amazonaws.com/WRIO-InternetOS/WRIO.js. main.js can be found here:
https://github.com/webRunes/WRIO-InternetOS/blob/master/WRIO.js
The page of http://webrunes.com here:
https://github.com/webRunes/webRunes-WRIO-Hub/blob/gh-pages/index.htm
You have to convert article-widget using react.js, it's build here, use view source page:
wrio.s3-website-us-east-1.amazonaws.com/Default-WRIO-Theme/widget/article.htm
from
https://github.com/webRunes/Default-WRIO-Theme/blob/gh-pages/widget/article.htm
Page http://webrunes.com/ have to be viewed ie10+ and firefox.

**Comment by AlexeyAnshakov** [comment]
Use https://scotch.io/tutorials/getting-to-know-flux-the-react-js-architecture (4 parts)

**Comment by sobi11** [comment]
ok

**Comment by sobi11** [comment]
I don't see anything  just lorem text
