### ISSUE TITLE
Longer ec2 resource ids

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#644]
Please check we're ready for
https://aws.amazon.com/blogs/aws/theyre-here-longer-ec2-resource-ids-now-available/?sc_channel=em&sc_campaign=longerec2idavailable_04252016&sc_publisher=aws&sc_medium=em_14615&sc_content=launch_la_nontier1&sc_country=global&sc_geo=global&sc_category=ec2&sc_outcome=launch&mkt_tok=eyJpIjoiTkRJNE56RTNZMk0yTXpJNCIsInQiOiJIZTNFYzRGd1NoaGZORWd0NFNzdm8rUWVOcXJUVmkzeVQ3VVBmZjRxc0NYc0Y5bEpPMVRVRmw1R3FocTlVRVRNMFZHSVJHbVd6cUVZOFpieGJWblhJY1ZcL3VsRnQyWWJlaXRSR0JQQW5TdU09In0%3D
so we won't face problems after dec 2016

**Comment by umairadeeb** [comment]
I don't think we need any changes. I will take a look at our cronjobs that
take snapshots of volumes.

**Comment by AlexeyAnshakov** [comment]
Can we close the task?
