### ISSUE TITLE
Autoclean old docker's containers

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#825]
Please create an autoclean script.

**Comment by AlexeyAnshakov** [comment]
@michbil  FYI

**Comment by michbil** [comment]
@umairadeeb we need some means to delete old docker images. i'm using script located /srv/docker/Wrio-Docker-Production/cleanup.sh
It shoud be scheduled to run once a week. Maybe you can find better solution.

Some links: 

https://forums.docker.com/t/command-to-remove-all-unused-images/20
https://gist.github.com/ngpestelos/4fc2e31e19f86b9cf10b

**Comment by umairadeeb** [comment]
@michbil: [This answer on stackoverflow](http://stackoverflow.com/questions/32723111/how-to-remove-old-and-unused-docker-images) has a very nice solution to this.

Here are the recommended commands to first cleanup exited containers and then remove unused images:

```
    docker rm -v $(docker ps --filter status=exited -q 2>/dev/null) 2>/dev/null
    docker rmi $(docker images --filter dangling=true -q 2>/dev/null) 2>/dev/null

```

Let me know if you think we should use this and I will then schedule it in cron.

**Comment by michbil** [comment]
@umairadeeb i've checked your scripts, works fine, please schedule to run it once a week

**Comment by umairadeeb** [comment]
Done.
Cron job has been configured to run the script once a week. You can check logs at /var/log/docker-cleanup.log
