### ISSUE TITLE
Reverse proxy. Reward 8 USD

### ISSUE THREAD

**Issue by AlexeyAnshakov** [webRunes/WRIO-InternetOS#96]
Set reverse proxy to redirect
54.235.73.25:5000 -> login.wr.io (created)
54.235.73.25:5001 -> titter.wr.io (created)

Help link
http://stackoverflow.com/questions/21589357/godaddy-domain-to-aws-ip-address-and-port

**Comment by umairadeeb** [comment]
This is completed.
